### ISSUE TITLE
Limitation of SSH remotes on CentOS

### ISSUE THREAD

**Issue by jeroen** [r-lib/gert#1]
CentOS ships with an old libssh2, which does not support modern ciphers required by Github. Basically we need at least libssh 1.7.0. See comment here: https://github.com/puppetlabs/r10k/issues/804#issuecomment-368619666.

For Ubuntu I created a [PPA with backports](https://launchpad.net/~opencpu/+archive/ubuntu/libgit2), but I am not sure how people deal with this on CentOS.

**Comment by triynko** [comment]
1.7 isn't even working against a private stash server.  I think 1.8.0 or 1.8.1 is necessary, but the damn source code never updated the version number. For example, the NuGet package for native binaries for 1.8.1 still serves a dll that says 1.7.0_DEV.  https://discourse.julialang.org/t/libssh2-on-windows/14193/5.  This all really needs an update ASAP.

**Comment by jeroen** [comment]
On CentOS 8 there is no libssh2 at all. I repoted it but [redhat doesn't seem to care]( https://bugzilla.redhat.com/show_bug.cgi?id=1830319):

> This was a deliberate decision, RHEL8 does not ship libssh2 (for security reasons IIRC) so we would have had to port libgit2 to a different library, and since libgit2 is primarily used for lorax-composer which doesn't need remote support it wasn't worth the effort to do that.

So there is not much we can do. I guess the best advice is to not use RHEL/CentOS.
