### ISSUE TITLE
installation of package ‘gert’ had non-zero exit status On Debian 9

### ISSUE THREAD

**Issue by yinshanfang** [r-lib/gert#112]
Hello, when I install package 'gert' , I get the following error information.

trying URL 'https://cloud.r-project.org/src/contrib/gert_1.0.2.tar.gz'
Content type 'application/x-gzip' length 61324 bytes (59 KB)
==================================================
downloaded 59 KB

* installing *source* package ‘gert’ ...
** package ‘gert’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lgit2
WARNING: your version of libgit2 is really old! HTTPS / SSH might not work
Configuration OK!
** libs
rm -f gert.so branch.o clone.o commit.o config.o conflicts.o files.o init.o merge.o rebase.o stash.o tag.o utils.o version.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS   -fvisibility=hidden -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/stretch/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c branch.c -o branch.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS   -fvisibility=hidden -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/stretch/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c clone.c -o clone.o
clone.c: In function ‘R_git_remote_ls’:
clone.c:436:11: error: too many arguments to function ‘git_remote_connect’
   bail_if(git_remote_connect(remote, GIT_DIRECTION_FETCH, &callbacks, NULL, NULL), "git_remote_connect");
           ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/git2/clone.h:14:0,
                 from /usr/include/git2.h:19,
                 from utils.h:1,
                 from clone.c:6:
/usr/include/git2/remote.h:247:17: note: declared here
 GIT_EXTERN(int) git_remote_connect(git_remote *remote, git_direction direction, const git_remote_callbacks *callbacks, const git_strarray *custom_headers);
                 ^~~~~~~~~~~~~~~~~~
/usr/lib/R/etc/Makeconf:168: recipe for target 'clone.o' failed
make: *** [clone.o] Error 1
ERROR: compilation failed for package ‘gert’
* removing ‘/home/yinshan2453/R/x86_64-pc-linux-gnu-library/3.6/gert’
Warning in install.packages :
  installation of package ‘gert’ had non-zero exit status

 sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.7.0
LAPACK: /usr/lib/lapack/liblapack.so.3.7.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3   

Does any one have this issue? Thank you.

**Comment by jeroen** [comment]
Gert requires at least libgit2 0.26. Debian 9 has been EOL as of 2020-07-06, but you can make it work by installing libgit2 from stretch-backports: https://packages.debian.org/stretch-backports/libgit2-dev

**Comment by jdblischak** [comment]
This took me a long time to debug, so I wanted to share my solution in case it could be helpful to others. I initially tried using the PPA as recommended in #107, but I couldn't get that to work on Debian (I tried changing the distribution to xenial and adding Jeroen's launchpad signing keys).

I test my package using multiple rocker images that use different versions of Debian:

* [r-ver:3.5.3](https://github.com/rocker-org/rocker-versioned/blob/8e6853dabecd8448ca95f1b85579243b9bc9f69e/r-ver/3.5.3.Dockerfile) -> debian:stretch
* [r-ver:3.6.3](https://github.com/rocker-org/rocker-versioned/blob/8e6853dabecd8448ca95f1b85579243b9bc9f69e/r-ver/3.6.3.Dockerfile) -> debian:buster
* [r-base:latest](https://github.com/rocker-org/rocker/blob/7f18e2cd64bbd40b683f3aacda9b2fc9c4991815/r-base/latest/Dockerfile) -> debian:testing

The main issue is Debian stretch. Here is how I installed libgit2-dev from stretch-backports as @jeroen recommended above.

```
apt update
apt install -y lsb-release
debian=`lsb_release --codename | cut -f2`
if [ $debian == 'stretch' ]
then
  echo 'Using stretch-backports to install libgit2-dev'
  echo 'deb http://deb.debian.org/debian stretch-backports main' >> /etc/apt/sources.list
  apt update
  apt install -y -t stretch-backports libgit2-dev
fi

apt-get install -y libgit2-dev
```

**Comment by yinshanfang** [comment]
Hi @jeroen and @jdblischak, I have solved this issue as you suggested. Thank you so much.

**Comment by paulchabotca** [comment]
> This took me a long time to debug, so I wanted to share my solution in case it could be helpful to others. I initially tried using the PPA as recommended in #107, but I couldn't get that to work on Debian (I tried changing the distribution to xenial and adding Jeroen's launchpad signing keys).
> 
> I test my package using multiple rocker images that use different versions of Debian:
> 
> * [r-ver:3.5.3](https://github.com/rocker-org/rocker-versioned/blob/8e6853dabecd8448ca95f1b85579243b9bc9f69e/r-ver/3.5.3.Dockerfile) -> debian:stretch
> * [r-ver:3.6.3](https://github.com/rocker-org/rocker-versioned/blob/8e6853dabecd8448ca95f1b85579243b9bc9f69e/r-ver/3.6.3.Dockerfile) -> debian:buster
> * [r-base:latest](https://github.com/rocker-org/rocker/blob/7f18e2cd64bbd40b683f3aacda9b2fc9c4991815/r-base/latest/Dockerfile) -> debian:testing
> 
> The main issue is Debian stretch. Here is how I installed libgit2-dev from stretch-backports as @jeroen recommended above.
> 
> ```
> apt update
> apt install -y lsb-release
> debian=`lsb_release --codename | cut -f2`
> if [ $debian == 'stretch' ]
> then
>   echo 'Using stretch-backports to install libgit2-dev'
>   echo 'deb http://deb.debian.org/debian stretch-backports main' >> /etc/apt/sources.list
>   apt update
>   apt install -y -t stretch-backports libgit2-dev
> fi
> 
> apt-get install -y libgit2-dev
> ```

This issue came up in BigSur and installing libgit2 via homebrew fixed it.
