### ISSUE TITLE
USE_SYSTEM_LIBGIT2=true the default unless libgit2-dev* is not available

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/gert#118]
@jan-glx wrote in https://github.com/r-lib/gert/issues/117#issuecomment-768266802:

> No. I was not aware gert is sideloading binaries. Does CRAN even allow this?

I thought about this too.  It's convenient but it might be considered anti-social and unsafe.  Here are a few problems with it:

* SECURITY: It downloads and runs http://r-lib.github.io/gert/get-libgit2-linux.sh over HTTP - not HTTPS
* SECURITY: Can the static library download URL (https://r-lib.github.io/gert/libgit2-1.1.0.x86_64_linux.tar.gz) be compromised
* SECURITY: What happens if https://r-lib.github.io/gert/libgit2-1.1.0.x86_64_linux.tar.gz stops being maintained and someone finds a security flaw in libgit2?  In contrast, here system libgit2 packages should be safer because this scenario is taken care of by big Linux distros
* STABILITY: What happens if https://r-lib.github.io/gert/libgit2-1.1.0.x86_64_linux.tar.gz is inaccessible or disappears? This depends on someone maintaining that download URL.  In contrast, CRAN is designed for a very long lifespan without relying on individual package maintainers
* OFFLINE: On systems without internet access that provide a local CRAN mirror (via `repos=file://...`), on-the-fly downloads from online sources during package installs will fail
 
# Suggestion

My proposal is to make `USE_SYSTEM_LIBGIT2=true` the default and only fall back to `USE_SYSTEM_LIBGIT2=` if there is no system libgit2-dev* available.

**Comment by jeroen** [comment]
> My proposal is to make USE_SYSTEM_LIBGIT2=true the default and only fall back to USE_SYSTEM_LIBGIT2= if there is no system libgit2-dev* available.

That is exactly what it does:

https://github.com/r-lib/gert/blob/6585a658b6fc88f90ae416ca6640532d1a07abae/configure#L21

On all recent linux distributions gert will use the system version of libgit2. This is also described in the NEWS

https://github.com/r-lib/gert/blob/6585a658b6fc88f90ae416ca6640532d1a07abae/NEWS#L1-L5

> SECURITY: Can the static library download URL be compromised

I don't see how. There is a much greater risk of your random local CRAN mirror getting compromised where you are installing unsigned packages, than the github URL getting compromised.

> What happens if https://r-lib.github.io/gert/libgit2-1.1.0.x86_64_linux.tar.gz is inaccessible or disappears?

Then the package will not use the static library method, and fall back to requiring the user to install libgit2.

> on-the-fly downloads from online sources during package installs will fail

Idem 

> What happens if https://r-lib.github.io/gert/libgit2-1.1.0.x86_64_linux.tar.gz stops being maintained

The static library is way more up to date than the thing you are getting in CentOS-7, which is effectively abandoned. It is maintained by the same person that maintains the gert package. Also it will no longer be needed once you upgrade to any current linux distribution.

> might be considered anti-social

This is really not the right word. I have gotten [a lot of crap](https://twitter.com/matloff/status/1350357628384264194) from people who insist that everything should "just work" with zero effort from their side. The fact that they would have to set some variable or install a system library has "broken their workflow".

So we do whatever we can to make things "just work" for most scenarios, even on a legacy operating systems, where the user [doesn't have permission](https://twitter.com/groundwalkergmb/status/1350336844022521857) to install a system library, or in CI scripts, where setting variables may be annoying. 

Hence we arrive at a compromise: if a recent enough version of libgit2 is available, such as on Ubuntu 20, Debian, Fedora, etc. we use this. OTOH, on legacy systems, such as centos-7 and ubuntu 16/18, we attempt to download the static library and use that. You can always opt-out by setting a variable. Also in case this fails, we fall back on the regular method, which is to inform the user that a recent enough version of libgit2 is needed and must be installed.

**Comment by HenrikBengtsson** [comment]
https://github.com/r-lib/gert/blob/6585a658b6fc88f90ae416ca6640532d1a07abae/configure#L21

Awesome.  I missed that (because of the below ...)

> ... This is also described in the NEWS

:+1: 


So, on CentOS 7 we only get `0.26.8`, which I think comes from [CentOS Extras](https://pkgs.org/download/libgit2).  This is < 0.28, which explains why installing **gert** 1.1.0 on CentOS 7 fell back to installing the static library.

Is that `--at-least=0.28`, correct? Is `--at-least=0.26` sufficient? (I hope so). Because in the DESCRIPTION, you specify `libgit2 (>= 0.26)`:

```r
> packageDescription("gert")[c("Version", "SystemRequirements")]
$Version
[1] "1.1.0"

$SystemRequirements
[1] "libgit2 (>= 0.26): libgit2-devel (rpm) or\nlibgit2-dev (deb). A PPA is available for older Ubuntu LTS\nversions."
```

In the past, I installed gert 1.0.1 using libgit2-dev 0.26.8, and yesterday I installed gert 1.1.0 w/ `USE_SYSTEM_LIBGIT2=true` on this system and "it seems to have worked".


>> What happens if https://r-lib.github.io/gert/libgit2-1.1.0.x86_64_linux.tar.gz is inaccessible or disappears?

> Then the package will not use the static library method, and fall back to requiring the user to install libgit2.

>> on-the-fly downloads from online sources during package installs will fail

> Idem

Beautiful; I just verified this by downloading the tarball and disabling my internet connection, e.g.

```sh
$ USE_SYSTEM_LIBGIT2="" Rscript --vanilla -e "install.packages('gert_1.1.0.tar.gz', repos=NULL)"
Installing package into ‘/home/hb/R/x86_64-pc-linux-gnu-library/4.0-custom’
(as ‘lib’ is unspecified)
* installing *source* package ‘gert’ ...
** package ‘gert’ successfully unpacked and MD5 sums checked
** using staged installation
> curl::curl_download("http://r-lib.github.io/gert/get-libgit2-linux.sh","get-libgit2-linux.sh")
Error in curl::curl_download("http://r-lib.github.io/gert/get-libgit2-linux.sh",  : 
  Could not resolve host: r-lib.github.io
Execution halted
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lgit2
Configuration OK!
...
```


> ... Also it will no longer be needed once you upgrade to any current linux distribution.

This is key, which I missed because you have the above fallback solutions in place.

>> might be considered anti-social

> This is really not the right word. ...

Sorry, I might not understand how to use that term. I thought it was a non-loaded term in programming.

I guess your work is sometimes a bit like that of a soccer referee - when things go well you hear nothing but as soon as there's a hiccup, you get the complaints.  But please know that there are lots of people out there that are appreciate all your hard work on bringing a smooth R experience to all of us across all platforms.

**Comment by HenrikBengtsson** [comment]
I can close this one but before doing so I want to make sure you saw my comment above about the configure script specifies `--atleast-version=0.28` whereas SystemRequirements specifies `libgit2 (>= 0.26)`.   Is that intentional, or is one of them a mistake?

**Comment by jeroen** [comment]
Yes it was intentional. The package can be compiled with 0.26, but it will work much better with a more recent version.

For example, you won't be able to clone from SSH remotes using the system libgit2 on CentOS.
