### ISSUE TITLE
`git_push()` crashes RStudio Server session in 1.1.0

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/gert#120]
We updated to gert 1.1.0 but unfortunately when we use `git_push()`, it crashes the open R session on our RStudio Server. When I re-installed 1.0.2, it worked again. We're on Ubuntu 16.04.6 LTS and previously installed the suggested ppa version (well, our admin did, anyway). It looks like 1.1.0 made changes related to that, so I'm not sure if that's why. 

There's a lot going on here, so I'm actually not sure what information would be helpful to you to hone in on this issue. Rather than trying to dump a bunch of system info to guess what might be, I'll wait for your guidance on what info you might need, if any.

**Comment by jeroen** [comment]
Does it not crash on the same server in the command line, only in rstudio?

Does it happen for other gert commands, or only for push? If so, for ssh or https remotes, or both? 

Can I reproduce this on rstudio cloud, or some other server? Can you show me your `gert::libgit2_config()`. I just tested on https://rstudio.cloud but that seems just fine:

<img width="586" alt="Screen Shot 2021-01-30 at 1 35 25 AM" src="https://user-images.githubusercontent.com/216319/106340879-8540c700-629b-11eb-9145-3d49782dd8ab.png">

**Comment by malcolmbarrett** [comment]
1. Only gert 1.1.0 commands *in* RStudio are crashing. `git push` works. using R in the command line + `gert::git_push()` works with gert 1.1.0. Rolling back to gert 1.0.2 works in RStudio. 
2. `gert::git_clone("https://github.com/r-lib/gert", "../gert")` crashed the session, too. I believe it is using https.
3. `gert::libgit2_config()`:
```r
$version
[1] ‘1.1.0’

$ssh
[1] TRUE

$https
[1] TRUE

$threads
[1] TRUE

$config.global
[1] "/home/malcolm.barrett/.gitconfig"

$config.system
[1] ""

$config.home
[1] "/home/malcolm.barrett"
```

**Comment by malcolmbarrett** [comment]
When I roll back to gert 1.0.2, `libgit2_config()` gives me the same output except for `$version`, which now says `0.27.7`

**Comment by jeroen** [comment]
Can you try installing gert like this, to see if that changes anything:

```r
Sys.setenv(USE_SYSTEM_LIBGIT2=1)
install.packages("gert", repos = 'https://cran.r-project.org')
```

**Comment by malcolmbarrett** [comment]
That worked! No crashes + successfully completed actions

**Comment by jeroen** [comment]
OK so than it has to do with the static version of libgit2 that we use. Perhaps it somehow conflicts with rstudio-server...

I can't reproduce the problem on my own rstudio server, but that one runs ubuntu 20.04. I'll try to see if I can reproduce this soon, at least you have a workaround for now.

Best solution would be of course if your sysadmin upgrades the server to a newer version of ubuntu (ubuntu 16 will be EOL in 3 months...)

**Comment by malcolmbarrett** [comment]
Thanks! Luckily, we're in the process of upgrading our server now, so I don't think it will be a long-term issue for us either way

I think I've reproduced it on RStudio Cloud, as well. It's here: https://rstudio.cloud/project/2128762

I ran:
```r
install.packages("gert", repos = 'https://cran.r-project.org')
gert::git_clone("https://github.com/r-lib/gert")
```

**Comment by jeroen** [comment]
I think this should be fixed now. Can you try again?

**Comment by malcolmbarrett** [comment]
🎉 The dev version works on both our server and on RStudio Cloud (https://rstudio.cloud/project/2129978). Thanks for the fast fix!!

**Comment by jeroen** [comment]
You don't need the dev version, the cran version will do :-) I updated the just script that we use to download the static libraries.

**Comment by malcolmbarrett** [comment]
🤯 

edit: just confirming that the CRAN version ALSO works for me 👍
