### ISSUE TITLE
Failed to install on CentOS 6

### ISSUE THREAD

**Issue by golivag** [r-lib/gert#124]
Hi,
I'm having issues installing gert on CentOS 6 machine. I got the following error:

** testing if installed package can be loaded
Error: package or namespace load failed for ‘gert’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/users/oliva/R/x86_64-pc-linux-gnu-library/3.5/gert/libs/gert.so':
  /home/users/oliva/R/x86_64-pc-linux-gnu-library/3.5/gert/libs/gert.so: undefined symbol: secure_getenv
Error: loading failed
Execution halted
ERROR: loading failed

any clue to solve this issue?
Thanks

**Comment by jeroen** [comment]
CentOS 6 has been EOL since november: https://wiki.centos.org/About/Product

You could try to install libgit2-devel yourself and then:

```r
Sys.setenv(USE_SYSTEM_LIBGIT2=TRUE)
install.packages("gert")
```

**Comment by golivag** [comment]
It worked, thank you very much!
