### ISSUE TITLE
support proxy authentication

### ISSUE THREAD

**Issue by espinielli** [r-lib/gert#13]
Given `usethis` will use `gert`, this issue is a plea to consider the possibility to support proxy authentication, see r-lib/usethis#863

**Comment by jeroen** [comment]
Which OS are you on? Did you try setting the curl proxy [environment variables](https://curl.haxx.se/libcurl/c/libcurl-env.html)?

**Comment by espinielli** [comment]
I am on MS Windows (at work) and have `http_proxy` and `https_proxy` set up.
They make my git or curl or... work from command line.

**Comment by jeroen** [comment]
I think this will be fixed in gert 1.0 because we now ship libgit2 1.0.0.
