### ISSUE TITLE
Expose `bare` argument of `git_repository_init()`

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/gert#130]
Pretty please!

**Comment by gaborcsardi** [comment]
👏

**Comment by jeroen** [comment]
Does it work?

**Comment by gaborcsardi** [comment]
Yep.

**Comment by gaborcsardi** [comment]
Btw, can you pls also bump to a dev version? Thanks!

**Comment by jeroen** [comment]
Feel free to commit small/medium non breaking changes directly, I really don't mind :-)
