### ISSUE TITLE
use_git() doesn't work

### ISSUE THREAD

**Issue by IanniMuliterno** [r-lib/gert#134]
I just started a project, then I tried to run `usethis::use_git()` and received the following : 

```r
> usethis::use_git()
√ Adding '.Rproj.user', '.Rhistory', '.Rdata', '.httr-oauth', '.DS_Store' to '.gitignore'
Error in libgit2::git_repository_open_ext : 
  failed to stat 'C:\Users\Iann<ed>/.gitconfig'
```

**Comment by jeroen** [comment]
@IanniMuliterno could you maybe test if this problem also exists with R 4.1 (aka R-devel): https://cran.r-project.org/bin/windows/base/rdevel.html

**Comment by jeroen** [comment]
@IanniMuliterno I have fixed this particular issue, but there are likely more problems with non-ascii usernames. I'll try to track these down, but you can make your life much easier by using a Windows username without diacritics 😄

**Comment by jeroen** [comment]
Small followup, did some more fixes, in particular to convert all paths to utf-8, which is what libgit2 expects: https://github.com/r-lib/gert/commit/ad1e7d402f5bd98d56b2e91522693dd2d7094127

 I think now everything should work for non-ascii users 😅

**Comment by IanniMuliterno** [comment]
Sorry for the delay everyone. @jeroen thank you very much!!!

**Comment by IanniMuliterno** [comment]
@jennybc yes, my username was an issue ahaha, In my experience special characters can be a headache to programmers who use windows
