### ISSUE TITLE
Can't install on Linux x86_64

### ISSUE THREAD

**Issue by tyleransom** [r-lib/gert#136]
I followed the communication on #117 but none of the proposed solutions works for me. I am running R 4.0.3 on RHEL 7 x86_64.

Here is my `sessionInfo()`:

<details>
<summary>sessionInfo()</summary>
<pre>
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3   
</pre>
</details>

When I simply type `install.packages("gert")` I get the following output:

<details>
<summary>Details</summary>
<pre>
pid 27167's current affinity mask: ff
pid 27167's new affinity mask: ff
* installing *source* package ‘gert’ ...
** package ‘gert’ successfully unpacked and MD5 sums checked
** using staged installation
pid 27183's current affinity mask: ff
pid 27183's new affinity mask: ff
> curl::curl_download("https://r-lib.github.io/gert/get-libgit2-linux.sh","get-libgit2-linux.sh")
> 
> 
pid 27223's current affinity mask: 1
pid 27223's new affinity mask: ff
> curl::curl_download('https://r-lib.github.io/gert/libgit2-1.1.0.x86_64_legacy-linux.tar.gz','bundle.tar.gz')
> 
> 
Using static libgit2-1.1.0 for Linux x86_64
Using PKG_CFLAGS=-DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include
Using PKG_LIBS=-L/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/lib -lgit2 -lrt -lpthread -lssh2 -lssl -lcrypto -ldl -lpcre -lz
Configuration OK!
** libs
rm -f gert.so branch.o clone.o commit.o config.o conflicts.o files.o init.o merge.o rebase.o stash.o submodules.o tag.o utils.o version.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c branch.c -o branch.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c clone.c -o clone.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c commit.c -o commit.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c config.c -o config.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c conflicts.c -o conflicts.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c files.c -o files.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c init.c -o init.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c merge.c -o merge.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c rebase.c -o rebase.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c stash.c -o stash.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c submodules.c -o submodules.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c tag.c -o tag.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c utils.c -o utils.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c version.c -o version.o
gcc -std=gnu99 -shared -L/opt/R/4.0.3/lib/R/lib -L/usr/local/lib -o gert.so branch.o clone.o commit.o config.o conflicts.o files.o init.o merge.o rebase.o stash.o submodules.o tag.o utils.o version.o -L/home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/lib -lgit2 -lrt -lpthread -lssh2 -lssl -lcrypto -ldl -lpcre -lz -L/opt/R/4.0.3/lib/R/lib -lR
/usr/bin/ld: /home/data/tmp/RtmpTJ71K2/R.INSTALL6a1f5dafc378/gert/libgit2/lib/libgit2.a(annotated_commit.c.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make: *** [gert.so] Error 1
ERROR: compilation failed for package ‘gert’
* removing ‘/home/user/R/x86_64-pc-linux-gnu-library/4.0/gert’
</pre>
</details>

When I do 

```r
Sys.setenv(USE_SYSTEM_LIBGIT2=1)
install.packages("gert")
```

I get the following:

<details>
<summary>Details</summary>
<pre>
trying URL 'https://cran.microsoft.com/src/contrib/gert_1.3.0.tar.gz'
Content type 'application/octet-stream' length 66410 bytes (64 KB)
==================================================
downloaded 64 KB

pid 28101's current affinity mask: ff
pid 28101's new affinity mask: ff
* installing *source* package ‘gert’ ...
** package ‘gert’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS= 
Using PKG_LIBS=-lgit2  
WARNING: your version of libgit2 is really old! HTTPS / SSH might not work
Configuration OK!
** libs
rm -f gert.so branch.o clone.o commit.o config.o conflicts.o files.o init.o merge.o rebase.o stash.o submodules.o tag.o utils.o version.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c branch.c -o branch.o
gcc -std=gnu99 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c clone.c -o clone.o
clone.c: In function ‘R_git_remote_ls’:
clone.c:421:3: error: too many arguments to function ‘git_remote_connect’
   bail_if(git_remote_connect(remote, GIT_DIRECTION_FETCH, &callbacks, NULL, NULL), "git_remote_c
   ^
In file included from /usr/include/git2/clone.h:14:0,
                 from /usr/include/git2.h:19,
                 from utils.h:1,
                 from clone.c:6:
/usr/include/git2/remote.h:247:17: note: declared here
 GIT_EXTERN(int) git_remote_connect(git_remote *remote, git_direction direction, const git_remote
                 ^
make: *** [clone.o] Error 1
ERROR: compilation failed for package ‘gert’
* removing ‘/home/user/R/x86_64-pc-linux-gnu-library/4.0/gert’
</pre>
</details>

One non-standard thing I have is that I have the following in my `.Rprofile` file which allows me to over-ride a build error that had been sending all R processes to a single core on my machine (see [here](https://stackoverflow.com/a/16794473/1311724) for context).

<details>
<summary>.Rprofile</summary>
<pre>
.First <- function() {
    system(sprintf("taskset -p 0xffffffff %d", Sys.getpid()))
}
</pre>
</details>

Any help would be appreciated. I do notice the warning message that "your version of libgit2 is really old! HTTPS / SSH might not work"

**Comment by jeroen** [comment]
Probably same as https://github.com/r-lib/gert/issues/129. Can you try `sudo yum install binutils` to update your `ld` ?

**Comment by tyleransom** [comment]
😌 That worked! Thanks so much. And sorry for missing #129.
