### ISSUE TITLE
Installation fails on ubuntu 18.04

### ISSUE THREAD

**Issue by yakov-g** [r-lib/gert#141]
As you can see there is `libgit2-26` installed (max version available on bionic), but libgert requires `r-cran-gert : Depends: libgit2-27 (>= 0.26.0) but it is not installable`

Step 8/22 : RUN apt list --installed | grep libgit2 &&     apt-get update &&     apt-get install -y         r-cran-recipes         r-cran-glmnet         r-cran-rjson         r-cran-e1071         r-cran-plumber         r-cran-caret         r-cran-tidyverse         r-cran-devtools         r-cran-pack         r-cran-rook         r-cran-littler         r-cran-usethis         r-cran-gert         r-base         r-base-dev &&     rm -rf /var/lib/apt/lists/
 ---> Running in 49d3805af2eb

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libgit2-26/bionic-updates,bionic-security,now 0.26.0+dfsg.1-1.1ubuntu0.2 amd64 [installed,automatic]
libgit2-dev/bionic-updates,bionic-security,now 0.26.0+dfsg.1-1.1ubuntu0.2 amd64 [installed]
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:6 http://ppa.launchpad.net/marutter/rrutter3.5/ubuntu bionic InRelease
Get:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Fetched 163 kB in 12s (14.1 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
r-base-dev is already the newest version (3.6.3-1bionic).
r-base is already the newest version (3.6.3-1bionic).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 r-cran-gert : Depends: libgit2-27 (>= 0.26.0) but it is not installable

**Comment by jeroen** [comment]
This is explained in the readme and also in the configure script if you install the package from source in R. If you want to use the binaries you can do this:

```
sudo add-apt-repository ppa:cran/libgit2
sudo apt-get install r-cran-gert
```

Or alternatively you can install gert from source in R, using `install.packages("gert")`.

The problem will also resolve itself when you upgrade to ubuntu 20.04.
