### ISSUE TITLE
Expose `git_branch_move()`

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#151]
I'm working on support in usethis for changing the default branch's name (locally and on GitHub) and (for a repo managed by someone else) detecting when the default branch has been renamed and adapting to that.

I really need `git_branch_move()`. Can that be exposed?

https://libgit2.org/libgit2/#HEAD/group/branch/git_branch_move

**Comment by jeroen** [comment]
OK it has been added.

**Comment by jennybc** [comment]
Thanks! Seems to be working as advertised.

**Comment by jeroen** [comment]
OK thanks for confirming
