### ISSUE TITLE
Installation of package ‘gert’ had non-zero exit status. Undefined symbol: EVP_PKEY_new_raw_private_key

### ISSUE THREAD

**Issue by greenjune-ship-it** [r-lib/gert#157]
Dear Team,

I have an issue with installation **gert** package. Here is the error message

```
Error: package or namespace load failed for ‘gert’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/iakovyu1/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-gert/00new/gert/libs/gert.so':
  /home/iakovyu1/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-gert/00new/gert/libs/gert.so: undefined symbol: EVP_PKEY_new_raw_private_key
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/iakovyu1/R/x86_64-pc-linux-gnu-library/4.0/gert’
Warning in install.packages :
  installation of package ‘gert’ had non-zero exit status
```
Here bellow I've attached the full log of installation in file.
[gert-installatoin-log.txt](https://github.com/r-lib/gert/files/7504327/gert-installatoin-log.txt)

I suppose that it might be related with this part of message `Undefined symbol: EVP_PKEY_new_raw_private_key`, but I have no idea, how to fix this.

May I kindly ask you to help me?

Best regards,
Yulia

**Comment by jeroen** [comment]
Looks like you have a conflicting version of openssl installed on your system in `/apps/easybuild/software/OpenSSL`. What operating system is this? What is this `/apps/easybuild` that you use to install? I have never seen this.

You probably need to either to uninstall OpenSSL form easybuild, or upgrade it to at least version 1.1.1. 

Or something else you can try is install libgit2 form easybuild: https://docs.easybuild.io/en/latest/version-specific/Supported_software.html?highlight=libgit2#list-software-libgit2-685

**Comment by Mycron** [comment]
Actually I fiind a solution for such case: the parent lua module R have to depends on OpenSSL 1.1.1 version to provide correct LD options for gert package installation process

**Comment by greenjune-ship-it** [comment]
Thanks to everyone, it works for me!
