### ISSUE TITLE
pack-refs?

### ISSUE THREAD

**Issue by wlandau** [r-lib/gert#158]
For what I am trying to do with `gert`, it would be really nice to have a wrapper around [`pack-refs`](https://git-scm.com/docs/git-pack-refs). Is this within scope?

**Comment by jeroen** [comment]
gert doesn't wrap `git` but libgit2. It is in scope if there is something similar in https://libgit2.org/libgit2/#HEAD

**Comment by wlandau** [comment]
Got it, thanks for explaining.
