### ISSUE TITLE
gert install centos7 R3.6

### ISSUE THREAD

**Issue by LiuKe98** [r-lib/gert#164]
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘gert’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/user/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-gert/00new/gert/libs/gert.so':
  /lib64/libgit2.so.26: undefined symbol: libssh2_userauth_publickey_frommemory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/user/R/x86_64-pc-linux-gnu-library/3.6/gert’

The downloaded source packages are in
	‘/tmp/Rtmp1R8Gm2/downloaded_packages’
Warning message:
In install.packages("gert") :
  installation of package ‘gert’ had non-zero exit status

**Comment by jeroen** [comment]
Please post the full log

**Comment by LiuKe98** [comment]
Millions for your help. The full log is that

trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/gert_1.4.3.tar.gz'
Content type 'application/octet-stream' length 67320 bytes (65 KB)
==================================================
downloaded 65 KB

* installing *source* package ‘gert’ ...
** package ‘gert’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lgit2
Configuration OK!
** libs
rm -f gert.so branch.o clone.o commit.o config.o conflicts.o files.o init.o merge.o rebase.o stash.o submodules.o tag.o utils.o version.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c branch.c -o branch.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c clone.c -o clone.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c commit.c -o commit.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c config.c -o config.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c conflicts.c -o conflicts.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c files.c -o files.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c init.c -o init.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c merge.c -o merge.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c rebase.c -o rebase.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c stash.c -o stash.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c submodules.c -o submodules.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c tag.c -o tag.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c utils.c -o utils.o
gcc -std=gnu99 -I"/opt/install.bak/R-3.6.3/lib64/R/include" -DNDEBUG -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c version.c -o version.o
gcc -std=gnu99 -shared -L/usr/local/lib64 -o gert.so branch.o clone.o commit.o config.o conflicts.o files.o init.o merge.o rebase.o stash.o submodules.o tag.o utils.o version.o -lgit2
installing to /home/users/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-gert/00new/gert/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘gert’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/users/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-gert/00new/gert/libs/gert.so':
  /lib64/libgit2.so.26: undefined symbol: libssh2_userauth_publickey_frommemory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/users/R/x86_64-pc-linux-gnu-library/3.6/gert’

The downloaded source packages are in
	‘/tmp/Rtmp1R8Gm2/downloaded_packages’
Warning message:
In install.packages("gert") :
  installation of package ‘gert’ had non-zero exit status

**Comment by LiuKe98** [comment]
>

**Comment by jeroen** [comment]
I am guessing you have two conflicting libgit2 installations on your machine. Probably one in `/usr/local/include` that you built yourself and then also the one in `/lib64/` that is part of centos `libgit2-devel`.

You need to remove either one or the other.

**Comment by LiuKe98** [comment]
Dear jeroen,
  Thanks for your helping. I tried to install the package again and realized the error was caused the confilct of two version curl. I removed one and resolved it.
LiuKe
