### ISSUE TITLE
Lost SSH support on macOS (arm)

### ISSUE THREAD

**Issue by pat-s** [r-lib/gert#171]
Since some weeks I've lost SSH support on macOS for some reason. I've browsed the package source but saw that in the end some C calls to libgit2 are made to infer SSH support. Given that I don't know much about this part, I decided to open this issue.

I've reinstalled {gert} multiple times. The same goes for libgit2 and libssh2. Wondering that nobody else yet reported something, hence I think it might be a local issue of mine?

- macOS 12.2.1 (arm)
- R 4.1.3
- libgit2 1.4.2
- libssh2 1.10.0
- {gert} installed from source

Any idea what might have changed? Some pkgconfig linking issue maybe? All other SSH related actions on my system works just fine.

**Comment by jeroen** [comment]
Why do you install gert from source, and not the binary package?

It depends on how you have built libgit2. Where did you get it from? The homebrew version of libgit2 supports libssh2, because it has this: https://github.com/homebrew/homebrew-core/blob/master/Formula/libgit2.rb#L25

A workaround is to build gert using autobrew libs, like so:

```r
Sys.setenv(CI=1)
install.packages("gert")
```

**Comment by pat-s** [comment]
> Why do you install gert from source, and not the binary package?

Personal pref (with one point being the testing of correct system libs linking)

> The homebrew version of libgit2 supports libssh2, because it has this: [https://github.com/homebrew/homebrew-core/blob/master/Formula/libgit2.rb#L25](https://github.com/homebrew/homebrew-core/blob/master/Formula/libgit2.rb?rgh-link-date=2022-03-14T16%3A01%3A18Z#L25)

Sorry, forgot to mention that it's the homebrew build (all formulas on my machine are from homebrew besides the R interpreter).
Hence I am somewhat confused what might be the issue here. I think the timestamp could somehow match the 1.3.0 -> 1.4.2 upgrade from `libgit2` even though I don't see any specific release notes WRT to SSH.
I assume v1.4.2 works for you in combination with {gert}?

(I can try to ask some colleagues of mine in the next days if they face the same issues)

**Comment by jeroen** [comment]
You are right, looks like a bug in homebrew. Fixed upstream here: https://github.com/Homebrew/homebrew-core/pull/96894

**Comment by jeroen** [comment]
The fix is merged in homebrew. So you should have ssh again after running `brew upgrade`.

**Comment by pat-s** [comment]
Thanks, works again!
