### ISSUE TITLE
Dynamic linking against newer libgit2 versions if available?

### ISSUE THREAD

**Issue by pat-s** [r-lib/gert#180]
### Scenario

- Ubuntu 20.04 with libgit 0.28.4 via APT
- Goal: support for `ed25519` SSH (which [seems to be supported since v1.2.0](https://github.com/libgit2/libgit2/pull/5750))

### Issues

- R binary builds from RSPM always link against their bundled version
- When attempting a source install, one first needs to set `USE_SYSTEM_LIBGIT2=1` to suppress using a static version of libgit2 and actually link against a newer system install of libgit2 (which are then found automatically)
- Even if linked successfully against a newer `libgit2`, subsequent reinstalls (which sometimes happen unnoticed in the background) of {gert} will change the `libgit2` version again to an old one

Is there a way to get dynamic support for linking against newer libgit2 versions? Is this a feature to consider for {gert}? I.e. could {gert} try to detect newer libgit2 installations (compared to the bundled and static ones) in well-known directories (e.g. `/usr/local`) and try to link against them automatically?

cc @krlmlr

**Comment by jeroen** [comment]
That is exactly how it works. If a local libgit2 v1.0 or newer is found, that is used. Otherwise it uses the static version.

https://github.com/r-lib/gert/blob/b44b3c2807d82ce780ddb319f1958b5a4f29a344/configure#L22

For example on CRAN check servers (debian and fedora) or ubuntu-22.04 it uses the local versions.

**Comment by krlmlr** [comment]
@pat-s: Could you please show a command line trace from a source install where the behavior that you describe occurs?

What does `gert::libgit2_config()` show?

**Comment by jeroen** [comment]
Does it help if I try to upgrade the static libgit2 build for linux? Currently it is using libgit2 1.1.0 (same as on e.g. ubunu 22.04)

**Comment by pat-s** [comment]
> That is exactly how it works. If a local libgit2 v1.0 or newer is found, that is used. Otherwise it uses the static version.

Thanks. AFAICS this only applies to source installs which is when the linking is done. I might have explained this point badly in the OP: source installs work fine if a newer `libgit2` is present. However, in our current use case, we mainly operate with binary packages (on Linux) which then use the bundled static `libgit2` (which as of now is v1.1.0) if no system lib is installed.

From a sysadmin perspective I would like to avoid the case of users linking against different versions of `libgit2` depending on the installation type of {gert}. 
Source installs are not an issue in general and the same goes potentially for differing versions of system lib dependencies but become problematic in environments solely focusing on the use of R binary packages and users which are not that familiar with upstream dependencies.

Would it technically be possible to first search for a local `libgit2` install for linking against the static bundled version?

> Does it help if I try to upgrade the static libgit2 build for linux? Currently it is using libgit2 1.1.0 (same as on e.g. ubunu 22.04)

That would help, yes! It would not solve the issue for older {gert} versions but might be the best way forward considering the points mentioned above?

Would a regular update policy of the bundled static libgit be helpful for users, e.g. once per year?

```sh
# install from source, linking against locally compiled libgit 1.6.0
USE_SYSTEM_LIBGIT2=1 R -q -e "install.packages('gert', repos = 'cloud.r-project.org', quiet = TRUE); gert::libgit2_config()$version"
> install.packages('gert', repos = 'cloud.r-project.org', quiet = TRUE); gert::libgit2_config()
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
$version
[1] ‘1.6.0’

# R binary pkg install, linking against bundled libgit2 
USE_SYSTEM_LIBGIT2=1 R -q -e "install.packages('gert', quiet = TRUE); gert::libgit2_config()$version"
> install.packages('gert', quiet = TRUE); gert::libgit2_config()
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
$version
[1] ‘1.1.0’
```

**Comment by jeroen** [comment]
> Would it technically be possible to first search for a local libgit2 install for linking against the static bundled version?

That is what happens, but this can only be done at built time. If you use pre-compiled packages, then the decision has been made for you. You cannot change this at runtime, if that is what you are asking.

I can try to update libgit2, but actually the static libgit2 on linux was only a workaround to deal with very old distros. I was hoping to gradually phase it out, as most current distros now ship libgit2 1.0 or newer. But from your post I figure that even even libgit2 1.1.0 is now dated and you need at least 1.2.0?

**Comment by pat-s** [comment]
> That is what happens, but this can only be done at built time. If you use pre-compiled packages, then the decision has been made for you. You cannot change this at runtime, if that is what you are asking.

Thanks for confirming, this is what I assumed!

> I can try to update libgit2, but actually the static libgit2 on linux was only a workaround to deal with very old distros. I was hoping to gradually phase it out, as most current distros now ship libgit2 1.0 or newer. But from your post I figure that even even libgit2 1.1.0 is now dated and you need at least 1.2.0?

I see the motivation for not including it (forever). In the end it's your decision, for users on Linux it might be helpful to cope with the often quite dated version via the official repos (or when `libgit2` is not installed at all). 

Given the fast moving `libgit2` with potential security fixes or other newly added support (like SSH key types here), having a recent `libgit2` version within the binary builds would be great.

And yes, I assume the minimum would be 1.2.0 but maybe you wanna go straight ahead to 1.6.0 even? (even though we don't have a real need for 1.6.0 atm)

**Comment by jeroen** [comment]
I have updated the static version to libgit2-1.5.0 now. So if you rebuild from source on a system that does not have libgit2 1.0 or newer, that is automatically used. But I don't think the RSPM binaries will be refreshed until a new release of gert.

But maybe you can go ahead and test that, if you install from source with the static version, your bug is solved?

**Comment by jeroen** [comment]
I've pushed out a new CRAN version 1.7.1 to trigger fresh builds of RSPM binaries with the new static libgit2.

**Comment by pat-s** [comment]
Thanks! This should solve the issue for the upcoming future, i.e. we can point users to use {gert} > 1.7.1 for `ed25519` SSH keys to work 🎉 

> So if you rebuild from source on a system that does not have libgit2 1.0 or newer, that is automatically used.

In our environment we try to avoid source installs and rely on CRAN snapshots for projects (with renv). While these cases will still not work as an older {gert} is usually used, users can bump to {gert} 1.7.1 in their project if this support is required. And it will of course work OOB for newer projects then.

@krlmlr This also means I will remove the APT install of `libgit2` in our environment as otherwise the updated bundled `libgit2` is not used.

**Comment by stephematician** [comment]
I believe this fails on i386 Ubuntu. I had to set `USE_SYSTEM_LIBGIT=1` otherwise it would fail to link to the static library.
