### ISSUE TITLE
Could git_commit_info() indicates whether a commit is a merge?

### ISSUE THREAD

**Issue by maelle** [r-lib/gert#182]
The output of `gert::git_log()` includes a "merge" variable, would there be an easy way to also have that variable in the output of `git_commit_info()`?

**Comment by jeroen** [comment]
You can infer this from the length of `$parents` in `git_commit_info()`. A merge commit has more than 1 parent.

**Comment by maelle** [comment]
Oh, thank you! :pray:  Makes sense :sweat_smile:
