### ISSUE TITLE
libgit2-dev on Ubuntu 20.04.5 LTS x86_64

### ISSUE THREAD

**Issue by wangzc66** [r-lib/gert#194]
Hi,
My OS is Ubuntu 20.04.5 LTS x86_64, and I have installed  [libgit2-dev (0.28.4+dfsg.1-2)](https://packages.ubuntu.com/focal/libgit2-dev).
However, according to the configure file, libgit2 requires at least version 1. So it will download a sh file from github, but it is difficult in China because of gfw.
I installed the library by exporting USE_SYSTEM_LIBGIT2=1 which avoids downloading files from github.
I noticed that libgit2-dev (0.28.4+dfsg.1-2) is also written in [the official document](https://docs.ropensci.org/gert/#the-libgit2-dependency).
Is libgit2 dev (0.28.4+dfsg. 1-2) compatible?

**Comment by jeroen** [comment]
Yes it is compatible. There are some new features in the latest libgit2 but those are not critical.
