### ISSUE TITLE
Jerry Johnson

### ISSUE THREAD

**Issue by krlmlr** [r-lib/gert#200]
The fledge package that uses gert in its tests. For some reason, after working on fledge (or on gert?), I sometimes end up with my global `.gitconfig` changed: user and e-mail is set to Jerry Johnson.

Example: https://github.com/cynkra/dm/pull/1912 (force-pushed after I noticed it). `jerry@gmail.com` seems to be a real user.

A Google search found exactly one relevant hit for Jerry Johnson: https://www.startpage.com/sp/search?query=%22jerry+johnson%22+%22jerry%40gmail.com%22&cat=web&pl=opensearch&language=english .

This has caused major pain because I typically notice it too late.  I don't have a username + email configured in my global `.gitconfig`, it's repo-specific for me: <https://www.cynkra.com/blog/2020-08-25-git-multiple-identities/>.

For now, I made `.gitconfig` read-only, let's see.

**Comment by jeroen** [comment]
I think the gert unit tests set a dummy user for commits in case no user is configured. We should probably unset that at the end, or skip the tests outside of CI.
