### ISSUE TITLE
Possible issue with gert in CRAN checks

### ISSUE THREAD

**Issue by cjvanlissa** [r-lib/gert#207]
Dear Jeroen e.a., I get the following error on Prof. Brian Ripley's test rig:

```
Error in libgit2::git_repository_open_ext : 
    could not find repository from '/data/gannet/ripley/R/packages/tests-Suggests/worcs.Rcheck/tests/testthat'
```

Is there any way to check if libgit is working properly, and making my tests conditional on that?

**Comment by jeroen** [comment]
I don't understand, what is the context? I'm not sure libgit2 is the problem here, but rather that the test tries to open a git repo where no exists?
