### ISSUE TITLE
Error when installing gert

### ISSUE THREAD

**Issue by hfl112** [r-lib/gert#208]
Got error when install gert. (R version 4.3.1)

** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘gert’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/hef/Tools/miniconda3/lib/R/library/00LOCK-gert/00new/gert/libs/gert.so':
  /home/hef/Tools/miniconda3/lib/R/library/00LOCK-gert/00new/gert/libs/gert.so: undefined symbol: getentropy
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/hef/Tools/miniconda3/lib/R/library/gert’
* restoring previous ‘/home/hef/Tools/miniconda3/lib/R/library/gert’

The downloaded source packages are in
        ‘/project02/gccri/hef/.tmp/RtmpCLB9Rk/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: package(s) not installed when version(s) same as current; use `force = TRUE` to
  re-install: 'sequenza'
2: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘gert’ had non-zero exit status

Any suggestions for this error?

**Comment by jeroen** [comment]
If you use conda it may be easier to install gert from anaconda: https://anaconda.org/conda-forge/r-gert 

Otherwise you need to show us the full install log and details about your platform and compilers.

**Comment by hfl112** [comment]
> If you use conda it may be easier to install gert from anaconda: https://anaconda.org/conda-forge/r-gert
> 
> Otherwise you need to show us the full install log and details about your platform and compilers.

Thanks , it worked!

**Comment by honghh2018** [comment]
I install in centos7.9  and then it get the same error,

I am manually install R package in centos7.9 not in virtualenv
The gcc version was 9.3.0
the openssl version was 3.0.7

R info:
> sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /share/apps/R/R-4.2.3/lib64/R/lib/libRblas.so
LAPACK: /share/apps/R/R-4.2.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.3 tools_4.2.3 
the error info:
4/R/lib -lR
installing to /share/apps/R/R-4.2.3/lib64/R/library/00LOCK-gert/00new/gert/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘gert’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/share/apps/R/R-4.2.3/lib64/R/library/00LOCK-gert/00new/gert/libs/gert.so':
  /share/apps/R/R-4.2.3/lib64/R/library/00LOCK-gert/00new/gert/libs/gert.so: undefined symbol: getentropy
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/share/apps/R/R-4.2.3/lib64/R/library/gert’



how to fix this issue ?
Best,
hanhuihong

**Comment by jeroen** [comment]
Can you show us the complete build output

**Comment by honghh2018** [comment]
The total build output lying below:
> install.packages('gert')
trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/gert_2.0.1.tar.gz'
Content type 'application/octet-stream' length 122723 bytes (119 KB)
==================================================
downloaded 119 KB

* installing *source* package ‘gert’ ...
** package ‘gert’ successfully unpacked and MD5 sums checked
** using staged installation
Found OpenSSL3
Using static libgit2 for Linux x86_64
Using PKG_CFLAGS=-DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include
Using PKG_LIBS=-L/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/lib -lstatgit2 -lrt -lpthread -lstatssh2 -lstatssl -lstatcrypto -ldl
Configuration OK!
** libs
rm -f gert.so branch.o clone.o commit.o config.o conflicts.o files.o ignore.o init.o merge.o rebase.o stash.o submodules.o tag.o utils.o version.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c branch.c -o branch.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c clone.c -o clone.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c commit.c -o commit.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c config.c -o config.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c conflicts.c -o conflicts.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c files.c -o files.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c ignore.c -o ignore.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c init.c -o init.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c merge.c -o merge.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c rebase.c -o rebase.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c stash.c -o stash.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c submodules.c -o submodules.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c tag.c -o tag.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c utils.c -o utils.o
gcc -I"/share/apps/R/R-4.2.3/lib64/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c version.c -o version.o
gcc -shared -L/share/apps/R/R-4.2.3/lib64/R/lib -L/usr/local/lib64 -o gert.so branch.o clone.o commit.o config.o conflicts.o files.o ignore.o init.o merge.o rebase.o stash.o submodules.o tag.o utils.o version.o -L/tmp/RtmptzFHBi/R.INSTALL54725abfec38/gert/libgit2-1.4.2-x86_64_linux/lib -lstatgit2 -lrt -lpthread -lstatssh2 -lstatssl -lstatcrypto -ldl -L/share/apps/R/R-4.2.3/lib64/R/lib -lR
installing to /share/apps/R/R-4.2.3/lib64/R/library/00LOCK-gert/00new/gert/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘gert’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/share/apps/R/R-4.2.3/lib64/R/library/00LOCK-gert/00new/gert/libs/gert.so':
  /share/apps/R/R-4.2.3/lib64/R/library/00LOCK-gert/00new/gert/libs/gert.so: undefined symbol: getentropy
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/share/apps/R/R-4.2.3/lib64/R/library/gert’

The downloaded source packages are in
	‘/tmp/RtmpKQ7vP1/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("gert") :
  installation of package ‘gert’ had non-zero exit status
Hope the resolve,

Best,
hanhuihong

**Comment by honghh2018** [comment]
Had any advices for this issue ?

**Comment by jeroen** [comment]
One workaround is to use the binary package form p3m. For example like so:

```r
install.packages('https://p3m.dev/cran/__linux__/centos7/latest/src/contrib/gert_2.0.1.tar.gz?r_version=4.2&arch=x86_64', repos = NULL)
```

If you really need to compile from source, try using the standard compiler. Temporarily set this in your `~/.R/Makevars` file:

```make
CC=/usr/bin/gcc
```

And then try reinstalling gert the normal way.

**Comment by honghh2018** [comment]
Thanks, it work when i install teh p3m package
install.packages('https://p3m.dev/cran/__linux__/centos7/latest/src/contrib/gert_2.0.1.tar.gz?r_version=4.2&arch=x86_64', repos = NULL)

**Comment by chaimol** [comment]
i am use R4.4 and centos7 system , it works by run 
```
install.packages('https://p3m.dev/cran/__linux__/centos7/latest/src/contrib/gert_2.1.4.tar.gz?r_version=4.4&arch=x86_64', repos = NULL)
```
