### ISSUE TITLE
Usage inside and outside of RStudio 

### ISSUE THREAD

**Issue by pat-s** [r-lib/gert#21]
Running certain functions that need the SSH keys like `gert::git_pull()` I get different outcomes based on whether I run them inside or outside of RStudio.

(The same applies for `git2r::pull()`)

Within RStudio everything works and it seems that RStudio is doing something behind the scenes to detect the SSH key / talk to the SSH-agent.

Within a plain R CLI session I get

```r
gert::git_pull()                                                 
Trying to authenticate 'git' using ssh-agent...
Error in git_fetch(info$remote, ..., repo = repo) : 
  libgit2 error in git_remote_fetch: error authenticating: failed connectin
g with agent (23)
```

Any idea what kind of initialization the CLI way might be missing out on?

macOS 10.15.4

**Comment by jeroen** [comment]
Can you add verbose=T to see what is happening?

**Comment by pat-s** [comment]
`verbose = TRUE` returns exactly the same error message for both `git_pull()` and `git_fetch()`.

**Comment by jeroen** [comment]
It depends a lot on which auth method you want to use. Do you have your key pre-loaded in ssh-agent or not? Can you show the output of rstudio when it does work? 

Can you check that the `SSH_AUTH_SOCK` environmet variable is the same in Rstudio and Rterm?

One difference is that rstudio sets environment variables `GIT_ASKPASS` and `SSH_ASKPASS` which help with entering a passphrase. But if your key is already loaded in ssh-agent that should not be needed.

**Comment by pat-s** [comment]
```r
# Rterm
Sys.getenv("SSH_AUTH_SOCK")
[1] "/Users/pjs/.gnupg/S.gpg-agent.ssh"

# RStudio
Sys.getenv("SSH_AUTH_SOCK")
[1] "/private/tmp/com.apple.launchd.IEkqbGMxgu/Listeners"
```

It's `SSH_AUTH_SOCK` because removing it within the RStudio sessions reproduces the error.
So something's wrong with the `gpg` SSH agent in Rterm.
I had set `SSH_AUTH_SOCK ~/.gnupg/S.gpg-agent.ssh` but that caused problems. Unsetting it helped to make everything work. Thanks for the pointer!
