### ISSUE TITLE
Add force argument to git_branch_create

### ISSUE THREAD

**Issue by M-Kusumgar** [r-lib/gert#238]
We would like to create a branch with a particular ref and if it exists then we would like to overwrite it. `libgit2::git_branch_create` has a `force` arg that already replicates this behaviour so would just be a case of adding the `force` arg to the `gert::git_branch_create`. I am happy to do a PR on this if you don't mind me adding this into `gert`!

**Comment by jeroen** [comment]
Yes, you can add a PR, thanks
