### ISSUE TITLE
Make pkgdown site easier to find

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#30]
How do you feel about various things?

Add pkgdown URL as main URL for this repo?

Put pkgdown site at gert.r-lib.org?

Migrate to most current tidyverse/r-lib pkgdown workflow (so ... via a GitHub Action)?

I can start implementing or making PRs.

**Comment by jennybc** [comment]
I see that `_pkgdown.yml` has some organization for the Reference page and yet that's not reflected in what I see here: <http://jeroen.cran.dev/gert/reference/index.html>

So I'm a bit puzzled about the pkgdown situation. My immediate context is looking for a better way of getting an overview of the functions in the package than reading `NAMESPACE`.

**Comment by jeroen** [comment]
Yes that's OK. I'm not a big fan of dragging around the entire website + full history in a branch of the code repository, but if that is the tidy way we can do it this way.

How do we register the subdomain?

**Comment by jennybc** [comment]
> How do we register the subdomain?

I would ask someone in the IT/devops team at RStudio to do it, I think.

**Comment by jeroen** [comment]
OK so I prefer to just the ropensci CI docs+cranlike server for now. It is also much faster and more robust than the GHA stuff, and we don't have to store the websites in the git repository.
