### ISSUE TITLE
Path preparation policy

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#35]
There are several instances of `normalizePath(path.expand(path), mustWork = FALSE)`.

1. Do you have any interest in pulling this out into a helper that implements a global gert policy on how user-specified paths are prepared?

2. Do you have any interest in signing on to fs? In particular, using fs's definition of home directory on Windows, which is generally more consistent with git, git bash, and basically all unix tools.

Context: I have done both of these in usethis. Even just doing 1 helps to clarify things, because I will know what I can count on re: gert's path handling. But doing 1 and 2 makes my life the easiest, because we would have the same policy.

**Comment by jeroen** [comment]
1 is OK, but 2 I'm not so sure. 

I totally agree that R's default HOME is very regrettable, but trying to override that my make things even more confusing. For example a user may do:

```r
dir.create("~/myrepo")
writeLines("blabla", "~/myrepo/test.txt")
git_init("~/myrepo")
```

And then these would point to different directories?

**Comment by jennybc** [comment]
> And then these would point to different directories?

Well, this is a sacrifice I've been willing to make in usethis. But it's true that path handling is more of an internal matter with usethis, i.e. the chance of our decision to embrace fs clashing with something a user has done is modest.

Confusion over the home directory has been an important part of the "can't find ssh credentials" story on Windows, for example.

https://www.onwebsecurity.com/configuration/git-on-windows-location-of-global-configuration-file.html

Where does libgit2 look (first?) for user's global git config on Windows? That is one reasonable definition of "home" worth considering. So, the rationale would be internal consistency.

I do think it's useful to make gert's convention around `~/`, whatever it is, explicit.

**Comment by jeroen** [comment]
Currently libgit2 inherits HOME from the R session but I'd like to change that: https://github.com/r-lib/gert/issues/48

**Comment by jennybc** [comment]
I just checked on git bash in my Windows VM and `~/` is `/c/users/jenny`. I haven't checked but I bet Windows Subsystem for Linux is same. So as far as examples like this go:

```
dir.create("~/myrepo")
writeLines("blabla", "~/myrepo/test.txt")
git_init("~/myrepo")
```

You could also imagine someone doing this in a git bash or WSL shell:

```
mkdir ~/myrepo
echo "blabla" > ~/myrepo/test.txt
```

Then wondering why `gert::git_init("~/myrepo")` creates an entirely new directory. Yes I realize this is more contrived. But I think you have a good chance right now to seriously consider going all in on *nix conventions, even on Windows. gert is a bit like usethis in that this mostly only matters at very specific times, like repo creation. And then further user <--> gert communication around file paths are relative to the repo.

**Comment by dpastoor** [comment]
Just to provide another portability frame of reference around this discussion - given gert's simple, intuitive interface its quickly been jumped on to be used across helper scripts and in fact for many newer (to git) users becomes the defacto interface for a lot of interactions beyond the rstudio git options. That said given the close mapping to the actual git commands, people are feeling more adventureous and empowered to bounce back and forth between the command line. 

The above example around switching between git bash and gert has already caused a couple head scratching moments. Our solution was to manually adjust R_HOME on any windows users laptops to mimic the unix style. 

In addition, more and more people are becoming polygots where they also will use some python/node/go or some other language where they are used to homedir expansion to feel consistent and are "growing" into R using things like fs from day 1.

Finally, the last use-case scenario we are seeing more-and-more of is people doing some work on laptops and maintaining a similar directory structure on linux accessible via rstudio server. Again the behavioral differences for some of the project bootstrapping and day-to-day chore activities that leverage gert that couldn't be purely relative-path based made it frustrating to users until the intervention.

Regardless, we love gert, and I know this is a very difficult design decisions that ultimately is going to frustrate some subgroup regardless of the ultimate decision, so I can't fault a decision one way or another, but just wanted to provide some other 'real-world' usage/feedback around the windows/unix differences.

**Comment by jeroen** [comment]
I'm very aware of the problems with this very unfortunate `HOME` default in R on Windows. This is also one of the pain points with rtools40. I have talked with Tomas Kalibera to change this in R 4.0 but I was not able to convince him. Maybe we should try again on a more public place so more people can chime in.

I fixed the problem with the global user `.gitconfig` which [is now consistent](https://github.com/r-lib/gert/issues/48) with R for Windows. 

However I'm still unsure about the paths for gert arguments. I'm afraid that if we will deviate from R here, gert will become incompatible with file operations from base R and other R packages that use the base R file APIs. 

Following principle of least surprise, I would personally be more surprised if different R packages use different path conventions, rather than differences between R and some external shell. For example in the msys2 shell, HOME is yet another location such as `C:/msys64/home/jeroen` so that is less of a surprise to me.

**Comment by jennybc** [comment]
> However I'm still unsure about the paths for gert arguments. I'm afraid that if we will deviate from R here, gert will become incompatible with file operations from base R and other R packages that use the base R file APIs.

Well, people can always do the expansion before handing their paths over to you, if they overtly disagree with your choice. If you use fs, this can also be explicitly configured via `R_FS_HOME` env var:

https://fs.r-lib.org/reference/path_expand.html

If you adopt *nix-style home directory, there are some advantages to using fs for it, i.e. you sort of pass the buck in terms of explaining it, it is configurable, it's consistent with a growing set of other packages that use fs.

> I'm very aware of the problems with this very unfortunate HOME default in R on Windows. This is also one of the pain points with rtools40. I have talked with Tomas Kalibera to change this in R 4.0 but I was not able to convince him.

Yeah, I would hope that maybe this is something R will change, a la `stringsAsFactors = FALSE`, changes around `c()` for factors, and the possible future hope of straightening out encoding on Windows. Sometimes I think change has to happen first in the add-on package world, to create the possibility of changing it in R itself. I sort of doubt `stringsAsFactors` would have ever changed without data.table and tidyverse breaking that ground.

I won't keep banging on about this. I think I've made all my arguments and will obviously accept whatever you decide.

**Comment by jeroen** [comment]
I want to keep the path consistent with the rest of R. I tried a few shells in Windows what `~` means to and they are all different: 
 - WSL: `\\wsl$\Ubuntu-20.04\home\username`
 - MSYS2: `C:\\msys64\\home\\username`
 - git bash: `C:\\users\username`
 - Base-R: `C:\\users\username\documents`

I very much agree that R should change the default, but there is no way for a package to go all in on *nix conventions by ourselves. It will just become very confusing when we use different conventions than base R and other packages that deal with files. 

```r
dir.create("~/myrepo")
git_init("~/myrepo")
```

If rstudio wants to go all-in on unix conventions, the IDE could automatically set `HOME`, and then R and all packages will automatically use that as `~`. But I don't think this is something packages should override.
