### ISSUE TITLE
Needs a general git_merge() function

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#41]
Right now, the only merge function if `git_branch_fast_forward()` but gert needs a more general function for merging.

**Comment by jeroen** [comment]
Yes I know. I've been putting that off because it's so complicated.

**Comment by jennybc** [comment]
Ah. FWIW this does come up pretty soon for me in my git2r --> gert conversion in usethis.

Do you want me to start taking a look or stab at this? I won't be as fast as you, I'm sure. But this is what I am working on right now.

**Comment by jeroen** [comment]
I'll have a look at it tomorrow... it's been a while since I looked at it but I was surprised how many steps and choices are involved in a merge operation.

**Comment by jeroen** [comment]
- libgit2 merge apis: https://libgit2.org/libgit2/#HEAD/group/merge
- libgit2 merge examples: https://github.com/libgit2/libgit2/blob/master/examples/merge.c
- git2r merge functions: https://docs.ropensci.org/git2r/reference/merge.html

**Comment by jeroen** [comment]
This is mostly there now, including a few unit tests.

I'm sure there are still loose ends, let's track those into separate individual issues.
