### ISSUE TITLE
Need to clarify what git_commit_all() does about new (untracked) files

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#42]
Currently `git_commit_all()` does not address new, untracked files.

``` r
library(gert)
#> Linking to libgit2 v0.28.4, ssh support: YES
#> Global config: /Users/jenny/.gitconfig
#> Default user: Jenny Bryan <jenny.f.bryan@gmail.com>

r <- tempfile(pattern = "gert")
git_init(r)
#> [1] "/private/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T/RtmpZKRbiJ/gert97c33bf58c92/"

writeLines(letters[1:6], file.path(r, "alphabet.txt"))
git_status(repo = r)
#> # A tibble: 1 x 3
#>   file         status staged
#> * <chr>        <chr>  <lgl> 
#> 1 alphabet.txt new    FALSE

# git_commit_all() does not work when there's only new files
git_commit_all("nope", repo = r)
#> Error in git_commit(message = message, author = author, committer = committer, : No staged files to commit. Run git_add() to select files.

git_add("alphabet.txt", repo = r)
#> <git repository>: /private/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T/RtmpZKRbiJ/gert97c33bf58c92[@NA]
git_commit("Start alphabet file", repo = r)
#> [1] "7ed57f6c53dfc2cba40ea2573fe540d1f5a01262"
git_status(repo = r)
#> # A tibble: 0 x 3
#> # … with 3 variables: file <chr>, status <chr>, staged <lgl>

writeLines(month.name[1:6], file.path(r, "months.txt"))
git_status(repo = r)
#> # A tibble: 1 x 3
#>   file       status staged
#> * <chr>      <chr>  <lgl> 
#> 1 months.txt new    FALSE

# git_commit_all() does not work when there's only new files
# second demo, to prove this has nothing to do with an unborn branch or whatever
git_commit_all("nope", repo = r)
#> Error in git_commit(message = message, author = author, committer = committer, : No staged files to commit. Run git_add() to select files.

cat(letters[7:9], file = file.path(r, "alphabet.txt"), sep = "\n", append = TRUE)
git_status(repo = r)
#> # A tibble: 2 x 3
#>   file         status   staged
#> * <chr>        <chr>    <lgl> 
#> 1 alphabet.txt modified FALSE 
#> 2 months.txt   new      FALSE

# this picks up only the modification to the tracked file
git_commit_all("Add more letters", repo = r)
#> [1] "27f0f048fcd0a4358b239dc52d7fdc72bd07931f"

# the new file is still there, unstaged, untracked
git_status(repo = r)
#> # A tibble: 1 x 3
#>   file       status staged
#> * <chr>      <chr>  <lgl> 
#> 1 months.txt new    FALSE

# cleanup
unlink(r, recursive = TRUE)
```

<sup>Created on 2020-06-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I suppose `git_commit_all()` is intended to emulate `git add -A && git commit -m "Your Message"` which *would* add new, untracked files?

@jeroen What do you want this function to do?

If current behaviour is intended, we should change the docs and maybe messaging.

Or we should change the behaviour to match `git add -A && git commit -m "Your Message"` and add & commit new, untracked, unignored files.

**Comment by jennybc** [comment]
For context, `git2r::commit(..., all = TRUE/FALSE, ...)` is relevant.

> `all` Stage modified and deleted files. Files not added to Git are not affected.

So git2r does *not* bring in new untracked files with its closest equivalent.

**Comment by jeroen** [comment]
`git_commit_all("commit all changes")` is supposed to do the same thing as

```
git commit -a -m "commit all changes"
```

This does not commit new untracked files; it only commits staged/changed/deleted files. I think we may need to fix the docs, but the behavior seems to match the command line?

**Comment by jennybc** [comment]
OK so the intent is for `git_commit_all()` to do `git commit -a -m "commit all changes"`, as opposed to `git add -A && git commit -m "Your Message"`.

At the very least, I think I will add more detail to the docs.

Do you still want throw this exact error?

```
#> Error in git_commit(message = message, author = author, committer = committer, : No staged files to commit. Run git_add() to select files.
```

The alternative would be to give more detail to help the person who doesn't realize that `git_commit_all()` can't see new, untracked files. This is a pure R function, so it would be relatively easy to provide better messaging.

**Comment by jeroen** [comment]
I think the error is indeed intended for users that have no staged changes, so probably they are unaware that they need to `git_add` new files before `git_commit` or `git_commit_all` will pick up on them. So I think it's a helpful message, no?

**Comment by jeroen** [comment]
Yes better docs and examples is always good. :)
