### ISSUE TITLE
Throw classed errors

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#46]
For downstream packages, it would be neutral-to-helpful if gert threw classed errors. At the very least, maybe adding its own class. But I think it could be very useful (and probably feasible?) to propagate that it's a libgit2 error (vs. R) and perhaps any error code libgit2 throws.

If you're willing to consider this @jeroen, it's something I would be willing to do some legwork or PRs on it.

**Comment by jennybc** [comment]
Enums re: libgit2's errors:

https://github.com/libgit2/libgit2/blob/86b85492b1bc8eeb9ff1af25b92877969f17833a/include/git2/errors.h

**Comment by jennybc** [comment]
Example of a task that would be cleaner with classed errors: detecting if we are working in a git repo. In usethis, we currently put `gert::git_find(path)` inside a `tryCatch()` and interpret any failure as "no, `path` is not / in not inside a git repo". But it would feel much better to build a proper function around this specifically, either in gert (#34) or in usethis.

**Comment by jeroen** [comment]
Thank you, great idea. I have added it, can you test if this covers your use cases (and maybe add a unit test)?
