### ISSUE TITLE
Submit gert to the list of language-specific libgit2 bindings

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#47]
https://github.com/libgit2/libgit2#language-bindings

**Comment by jennybc** [comment]
libgit2's enum for error classes:

https://github.com/libgit2/libgit2/blob/86b85492b1bc8eeb9ff1af25b92877969f17833a/include/git2/errors.h#L74-L112

**Comment by jeroen** [comment]
Let's do that after the 1.0 releaese.

**Comment by jeroen** [comment]
--> https://github.com/libgit2/libgit2/pull/5795

**Comment by jeroen** [comment]
Done! Thanks :)
