### ISSUE TITLE
Try to use USERPROFILE as HOME on Windows

### ISSUE THREAD

**Issue by jeroen** [r-lib/gert#48]
Regrettably R for Windows set the `HOME` variable to the Documents folder and libgit2 [will respect that](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) choice. As a result, the default config directory is different than in git for windows.

Maybe we should modify libgit2 for windows to always use USERPROFILE instead of HOME.

**Comment by jennybc** [comment]
Dropping the same link as I did in #35 because it lays out the whole, confusing situation very nicely:

https://www.onwebsecurity.com/configuration/git-on-windows-location-of-global-configuration-file.html

I would also prefer treating USERPROFILE as the default for "place where user / global config is". Which is related to #35, where part of what I'm advocating for is embracing that (really the *nix convention) for home directory as well.

**Comment by edonnachie** [comment]
Thank you for the explanation and link.

I have the same problem on a Windows virtual session (VMWare Horizon):

- Both git2r and git for Windows have global config under "H:\\.gitconfig"
- gert looks instead under "C :\Users\USER\\.gitconfig" (the session profile, which with the exception of a few defined locations is wiped on logout)

The only solution that works for me is to add this to the .Rprofile:

```{r}
if (file.exists("h:/.gitconfig")) {
  file.copy("h:/.gitconfig", file.path(Sys.getenv("USERPROFILE"), ".gitconfig"))
}
```

**Comment by jeroen** [comment]
So your `Sys.getenv("HOME")` is set to `H:/` but `Sys.getenv("USERPROFILE")` is just `C :\Users\USER`?

**Comment by edonnachie** [comment]
Things get complicated with a virtual session. I have:

```
> Sys.getenv("HOME")
[1] "\\\\SERVER\\VDIProfiles$\\USER\\Documents"
> Sys.getenv("USERPROFILE")
[1] "C:\\Users\\USER"
> Sys.getenv("R_USER")
[1] "H:/"
```

HOME is the remote VDI profile, USERPROFILE is a local version on the virtual session. I had to set R_USER to H:/ because knitr/rmarkdown had trouble with the windows UNC path.

**Comment by jeroen** [comment]
How does git for windows end up at `H:\` then? I would expect it to respect `$HOME`

**Comment by edonnachie** [comment]
The environment variable %HOME% is not defined in the config window and not available from cmd:

```
H:\>echo %USERPROFILE%
C:\Users\USER

H:\>echo %HOME%
%HOME%
```

So I have no idea where R gets HOME from (it's not in Renviron or Rprofile), or why git uses H:. 

I will investigate further, but perhaps the issue is that there's not a clear $HOME. Sometimes the remote profile is used, sometimes the temporary local profile (which is populated from the remote profile when the session is initialised).

**Comment by edonnachie** [comment]
It looks like %HOME% is derived from these:

HOMEDRIVE=H:
HOMEPATH=\
HOMESHARE=\\SERVER\HOME

where H: is mapped to %HOMESHARE%/%HOMEPATH%

Seemingly, HOMEDRIVE/HOMEPATH is usually the same as USERPROFILE, but not in my case.

So my guess is that R, git2r and git for Windows are correctly using these variables, but gert/libgit2 is not.

See also: https://stackoverflow.com/questions/606483/what-is-the-meaning-of-these-windows-environment-variables-homedrive-homepath

**Comment by jeroen** [comment]
I'm surprised your configuration works with git-for-windows, because if I look at the git source code it should only pick that up when both HOMEDRIVE and HOMEPATH are set, and in your case the latter seems empty: https://github.com/git/git/blob/e5a14ddd2d93da4d951fd63d4f78fe2410debe68/compat/mingw.c#L2607-L2615

**Comment by jeroen** [comment]
See also this text: https://github.com/git-for-windows/git/commit/6fbd39610c6c60018b7be5cf219febcea29df43c

```
Git will set a process environment variable equal to:
	`$HOMEDRIVE$HOMEPATH` if both `$HOMEDRIVE` and `$HOMEPATH` exist;
	otherwise `$USERPROFILE` if `$USERPROFILE` exists.

```

**Comment by jeroen** [comment]
Pushed a fix here to match the behavior for git-for-windows: https://github.com/r-lib/gert/commit/a515651fe19c24acc13e6e8a32cf553a4fa7d8a5. @edonnachie can you test this pls?

Get the latest version from: `install.packages("gert", repos = "https://r-lib.r-universe.dev")`

**Comment by edonnachie** [comment]
Thank you, the update works (with the copied .gitconfig removed).

My HOMEPATH is not empty, but is a backslash, which is why it doesn't display above.
