### ISSUE TITLE
Ponder what git_push() does re: configuring a tracking branch

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#51]
Summarizing a Slack conversation.

The current behaviour of `git_push()` sets upstream tracking branch if the branch we're pushing doesn't have a tracking branch yet:

https://github.com/r-lib/gert/blob/master/R/fetch.R#L75-L77

Translating to command line git, this does `git push -u` or `git push --set-upstream`. However that's not the default for the command line, i.e. you have to really request that behaviour.

At the very least this should be documented.

Open question: should `git_push()` gain some sort of argument and put this under its control?

**Comment by jennybc** [comment]
Some relevant context is that the main point of a tracking branch is to govern what happens for an argument-less `git pull`. Tracking branch is also relevant for `git push`, but the connection is more complicated and influenced by a few interacting pieces of config.

**Comment by jennybc** [comment]
My hunch (and it's just a hunch) is that there should be an argument (maybe `set_upstream`?) that takes logical, defaulting to `NA`, which implements current behaviour. But an explicit `TRUE` or `FALSE` can also be supplied. That feels like the right functionality and a formal argument gives a place to hang some documentation.

**Comment by jeroen** [comment]
Yes that makes sense.

**Comment by jeroen** [comment]
OK I implemented your suggestion, but instead of `NA` I use `NULL` as the default (hadley once told me that he likes `NULL` to be the explicit default behavior).
