### ISSUE TITLE
git_remote_add() return value is odd

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#55]
This seems weird to me:

```
> git_remote_add(
+   "origin",
+   "https://github.com/jennybc/whatever.git"
+ )
character(0)
```

Should that at least be invisible? Also wondering, if it doesn't have content, should it be `NULL`?

If it's not `invisible(NULL)` should it be `TRUE` indicating success? Or the name of the remote or the URL?

**Comment by jeroen** [comment]
Yes I guess that makes sense. Or we could return `git_remote_list()` maybe?

**Comment by jennybc** [comment]
I don't have a strong opinion. But I guess it should either be invisible `NULL` or `TRUE`. But if we fail, we'll error, so not sure there's any argument for returning `TRUE` as opposed to `NULL`.
