### ISSUE TITLE
R_git_branch_set_upsteam --> R_git_branch_set_upstream (typo, missing 'r')

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#61]
I'm having trouble using `git_branch_set_upstream()` and, while I study that I notice this typo. It is made consistently, so it's not causing a problem, but presumably it would be good to fix.

https://github.com/r-lib/gert/blob/b68822e9ee449d5e4b3009cf82d705e64411f528/R/branch.R#L69

**Comment by jeroen** [comment]
Oops, thanks!
