### ISSUE TITLE
`remote` argument of `git_branch_set_upstream()` needs better documentation

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#62]
I think the `remote` argument of `git_branch_set_upstream()` actually needs to be of the form "REMOTE/BRANCH", yes? I came to this conclusion based on reading some source and experimentation.

https://github.com/r-lib/gert/blob/5193a691115863781e35c5f70bed6072a8161594/R/fetch.R#L95

I took me a while to figure out how to use it since its default value is `remote = "origin"` and its docs say:

> `remote` name of existing remote from `git_remote_list()`

**Comment by jeroen** [comment]
Yes you're right, it should probably be called `branch` instead of `remote`. Technically git also allows you to use another local branch as the upstream, I'm not sure if that is useful to support.

**Comment by jeroen** [comment]
There are some more inconsistent parameter names in ?git_branch. Need to revise this.

**Comment by jeroen** [comment]
Renamed parameter to `upstream` and documented.
