### ISSUE TITLE
Allow remote to be specified with `git_pull`

### ISSUE THREAD

**Issue by rundel** [r-lib/gert#63]
Currently `git_pull` will only use the upstream remote. I think it makes sense to allow the user to provide the remote with a failover to upstream?

I'm happy to put together a pull request if this is useful.

**Comment by jeroen** [comment]
Yeah if the command line supports that we can add it to gert. Can you propose a pr?

**Comment by rundel** [comment]
This kind of thing is allowed from the command line, particularly if you don't have an upstream set.

From my basic experimenting it looks like 
```
git pull origin test
```
fetches `origin/test` and then merges it into the local `test` branch. 

The issue I am seeing at the moment is that the current implemented version of `git_merge` only supports merging the given ref directly into the current local branch. It seems possible but hacky to switch branches before merging and then switching back after.

I can take a look at what the other wrapper libraries do and see if I can come up with a possible PR that doesn't affect too many bits - this doesn't seem worth creating too much turmoil as I don't actually have a use case for this at the moment just came across the issue when I was debugging something else.

**Comment by rundel** [comment]
Actually this isn't as bad as I thought - I just needed to look back over the refspec docs. I'll see what I can come up with this afternoon.

**Comment by jeroen** [comment]
Maybe for now we just implement 'git pull myremote' so just only support the current branch? Most gert apis are limited to the current branch, so you just need to checkout first if you want to work on another branch.

**Comment by rundel** [comment]
This is definitely the right call - having to worry about the banch / ref makes things way worse. Also doing something like `git pull origin test` seems to only take care of the fetch and does not perform the merge (unless you are in the test branch already) which seems not very useful. Seems better to leave it up to the user to switch to the desired branch and then pull.
