### ISSUE TITLE
Path to my git config file has been realized

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#67]
When I attach gert, I see this:

```
> library(gert)
Linking to libgit2 v0.28.4, ssh support: YES
Global config: /Users/jenny/resources/system-setup/dotfiles/DOTgitconfig
Default user: Jenny Bryan <jenny.f.bryan@gmail.com>
```

Note the path reported for my user-level / global config. I have this symlinked elsewhere, because I actually keep it under version control, along with other dot files.

This seems a bit undesirable, i.e. it would be more expected to see `~/.gitconfig` or `/Users/Jenny/.gitconfig`. This is one of the downsides of `normalizePath()` vs. some of the functions in fs.

``` r
normalizePath("~/.gitconfig")
#> [1] "/Users/jenny/resources/system-setup/dotfiles/DOTgitconfig"
fs::path_real("~/.gitconfig")
#> /Users/jenny/resources/system-setup/dotfiles/DOTgitconfig

fs::path_expand("~/.gitconfig")
#> /Users/jenny/.gitconfig
fs::path_norm("~/.gitconfig")
#> ~/.gitconfig
```

<sup>Created on 2020-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I'm probably a bit unusual, but I bet other people also do what I do, for the same reason. It's not a huge deal, but worth considering if this can be prevented.

For comparison, here's what I see in the shell with `git config --list --show-origin`:

```
jenny@2020-mbp ~ $ git config --list --show-origin
file:/Library/Developer/CommandLineTools/usr/share/git-core/gitconfig   credential.helper=osxkeychain
file:/Users/jenny/.gitconfig    user.name=Jenny Bryan
file:/Users/jenny/.gitconfig    user.email=jenny.f.bryan@gmail.com
file:/Users/jenny/.gitconfig    core.editor=emacs
file:/Users/jenny/.gitconfig    core.excludesfile=/Users/jenny/.gitignore_global
file:/Users/jenny/.gitconfig    credential.helper=osxkeychain
file:/Users/jenny/.gitconfig    commit.template=/Users/jenny/.stCommitMsg
file:/Users/jenny/.gitconfig    push.default=current
```

**Comment by jennybc** [comment]
I just noticed that the realization is being done in `.onAttach()`.

https://github.com/r-lib/gert/blob/47260baafb81b153cede05f788c652ce268044d5/R/init.R#L8-L10

The "raw" result returned by `libgit2_config()` has one of the paths I expected to see:

``` r
gert::libgit2_config()$config.global
#> [1] "/Users/jenny/.gitconfig"
```

Obviously you are aware of this 😁 @jeroen, but it makes me realize it would be a relatively easy change.

Is the explicit use of `normalizePath()` motivated by something specific? I'm guessing home directory confusion on Windows?

**Comment by jeroen** [comment]
Yes it was indeed because on Windows the raw path had a mix of backslashes and forward slashes in my case, so I thought it would be better to show the path in the canonical notation.

I'll just special case this for Windows.
