### ISSUE TITLE
Tickle RStudio's Git pane

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#69]
It would be cool if git operations carried out by gert were generally reflected in the RStudio Git pane. I'm thinking about which branch we're on, mainly. Probably also the adead/behind summary?

You'd need to Suggest rstudioapi then wrap up a little helper like the one we use in usethis (we Import because we use rstudioapi in other ways), and put it inside `on.exit(add = TRUE)` for any operations that might influence the passive look of the Git pane:

https://github.com/r-lib/usethis/blob/fb6e390bf874462ffab803df2319f8a982a0848f/R/rstudio.R#L173-L178

```
rstudio_git_tickle <- function() {
  if (rstudioapi::hasFun("executeCommand")) {
    rstudioapi::executeCommand("vcsRefresh")
  }
  invisible()
}
```

**Comment by jeroen** [comment]
Cool, yes I like that. But I think almost all operations need to do this then? For example `git_add()` and `git_commit` are very cool if you see it happening visually.

Also we need to condition on `Sys.getenv('RSTUDIO')` and probably `interactive()`

**Comment by jennybc** [comment]
I agree you should err on the side of "do it" (tickle) vs. not.

Maybe @jmcphers can comment on which other conditioning is "worth it" and/or not already implemented inside rstudioapi.

It's true that gert is much more likely to be used noninteractively than usethis.

**Comment by jeroen** [comment]
It looks like the performance overhead of tickling is basically zero, so I'm just going to add it for every call, and see how that feels.

**Comment by jeroen** [comment]
Wow this is super nice. I did `git_add()` and then `git_commit()` and then `git_push()` and it gave me live visual feedback about what I was doing. Super helpful!
