### ISSUE TITLE
Add `track` argument to `git_branch_create()`

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#71]
If you create and checkout a local branch with a remote branch as start point, that remote branch is also set as the upstream tracking branch:

```
jenny@2020-mbp susan $ git checkout -b toby origin/toby
Branch 'toby' set up to track remote branch 'toby' from 'origin'.
Switched to a new branch 'toby'

jenny@2020-mbp susan $ git branch -vv
  master ff9ad4f [origin/master] Add cherry
  test   26d70dd Add cherry
* toby   2d3df6e [origin/toby] Add durian
```

Maybe gert could offer the same service in `git_branch_create()`?

Relevant excerpt from `git branch` docs (<https://git-scm.com/docs/git-branch#_description>)

> When a local branch is started off a remote-tracking branch, Git sets up the branch (specifically the `branch.<name>.remote` and `branch.<name>.merge` configuration entries) so that `git pull` will appropriately merge from the remote-tracking branch. This behavior may be changed via the global `branch.autoSetupMerge` configuration flag. That setting can be overridden by using the `--track` and `--no-track` options, and changed later using `git branch --set-upstream-to`.

More specific details re: `-t / --track` options for `git branch` and `git checkout -b`:

<https://git-scm.com/docs/git-branch#Documentation/git-branch.txt--t>

> When creating a new branch, set up `branch.<name>.remote` and `branch.<name>.merge` configuration entries to mark the start-point branch as "upstream" from the new branch. This configuration will tell git to show the relationship between the two branches in `git status` and `git branch -v`. Furthermore, it directs `git pull` without arguments to pull from the upstream when the new branch is checked out. This behavior is the default when the start point is a remote-tracking branch.

**Comment by jeroen** [comment]
<img width="678" alt="Screen Shot 2020-07-09 at 10 57 36 PM" src="https://user-images.githubusercontent.com/216319/87090491-5ea43b80-c238-11ea-8944-7e21501126fc.png">

---

OK so based on my reading of the above, the solution is:

In `git_branch_create()`, if `ref` (the source) is a remote branch, then we should automatically set the upstream of the newly created branch to `ref`.

**Comment by jeroen** [comment]
I have also implemented the above described "shortcut" here: https://github.com/r-lib/gert/commit/61e0e7e8de41509f2b9d7b59491f27ea7a0fc91e

So if you checkout a branch that does not exist locally yet, but there is exactly one remote that has that branch, the local branch will automatically be created.
