### ISSUE TITLE
Make git_remote_set_url() less permissive or smarter

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#72]
As discussed in Slack.

`git_remote_set_url()` "works" even if there is no pre-existing remote named `name`. It does add such a remote to `.git/config`. But it looks like this:

```
[remote "upstream"]
	url = git@github.com:cran/TailRank.git
```

However a properly configured remote looks like this (note the refspec):

```
[remote "upstream"]
	url = git@github.com:cran/TailRank.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
```

To add a new remote, you really need to call `git_remote_add()`.

This lack of refspec is a rather subtle misconfiguration and it's quite hard to figure out what you've done wrong from error messages you see when, e.g., merging and pushing.

I propose one of these solutions:

1. `git_remote_set_url()` errors if no remote named `name` exists. Recommend to call `git_remote_add()`?
2. `git_remote_set_url()` delegates to `git_remote_add()` if no remote named `name` exists.

**Comment by jeroen** [comment]
I agree that libgit2 is a bit too lenient here, and that implicitly creating the remote (without a refspec) is undesired in our case. 

When I looked into this, I also saw some opportunities for other refactoring/improvement, but I'll wait with this until after your presentation.
