### ISSUE TITLE
Add a Vignette :D

### ISSUE THREAD

**Issue by jtelleriar** [r-lib/gert#8]
It would be a great idea to add to the Library a Vignette! :)

Do you accept contributions in that sense?

I could include in it some GIT Theory from MIT: http://web.mit.edu/cluedumps/slides/understanding-git-2008.pdf

Some of Gitlab's Cheatsheet Core Concepts:
https://about.gitlab.com/images/press/git-cheat-sheet.pdf

And even recommend the use of one of the best GIT Client out there:
https://www.gitkraken.com/git-client

**Comment by jennybc** [comment]
I've started a basic gert vignette now and as I get to know more functions, I will keep adding to it.
