### ISSUE TITLE
Send messages to standard output in interactive sessions

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#83]
After switching usethis to gert, I get many opportunities to compare and contrast the messaging from usethis and gert.

<img width="879" alt="Screen Shot 2020-07-28 at 1 42 19 PM" src="https://user-images.githubusercontent.com/599454/88719508-3e013000-d0d8-11ea-9876-75c4354132a7.png">

In many places, I will probably ultimately use `verbose = FALSE` or other methods to suppress gert output.

But it brings up a general point: it seems that users often don't read text that looks like an error, which is the case for the reddish orange output coming from gert here (and elsewhere).

usethis runs all user messaging through `rlang::inform()` in order to get this behaviour introduced in rlang 0.4.2 (quoting from its NEWS file):

`inform()` now prints messages to the standard output by default in interactive sessions. This makes them appear more like normal output in IDEs such as RStudio. In non-interactive sessions, messages are still printed to standard error to make it easy to redirect messages when running R scripts (#852).

Would you ever consider doing same, either via rlang or by inlining similar logic?

**Comment by jeroen** [comment]
So something along the lines of this?

```r
inform <- function(...){
  if(interactive())
    cat(..)
  else
    message(...)
}
```

I don't understand the use-case though. So RStudio tries to be helpful and distinguish stdout vs stderr via coloring, and we now want to undo this behavior to make messages appear like print again in RStudio?

**Comment by jennybc** [comment]
I'll post an excerpt here from a conversation that eventually covered this ground on r-pkg-devel, once the world decided I needed to be taught how to use `message()` 🙄. This was written by @jimhester.

> Unfortunately, in the real world, the windows R gui console and RStudio (which copied behavior) color messages, and anything on stderr in fact, in red, which confuses most users who are trained to treat messages in red as errors.
>
> This also makes using colored output (where available) more challenging when using `message()`.  You either have to accept the text as red, or unconditionally change the text color to black or similar, which can then be unreadable if the user is using a dark color theme.

So, this is why, in the past, usethis used `cat()` for informational messages. Once `rlang::inform()` got this more attractive behaviour, we switched to routing all user messaging through it.

**Comment by jeroen** [comment]
OK if `cat()` looks better than `message()` within interactive sessions, we could do that. I don't have a strong preference. But I prefer not to depend on rlang just for this. Does `rlang::inform()` have any other special benefits, or can we just use `cat()` directly?

**Comment by jennybc** [comment]
From where I sit, yeah, this is really mostly about whether we communicate via stdout vs. stderr:

https://github.com/r-lib/rlang/blob/2d4823a15f4ae9cde922ff08c72702b9a7394074/R/cnd-signal.R#L159-L160

**Comment by jimhester** [comment]
It would be better to continue to use `message()` then just a bare `cat()`.

Instead you should still send a condition, but print it differently if interactive than otherwise, e.g. something like this

```r
inform <- function(message) {
  cnd <- structure(list(message = paste0(message, "\n")), class = c("message", "condition"))
  withRestarts(muffleMessage = function() NULL, {
    signalCondition(cnd)
    cat(conditionMessage(cnd), file = if (interactive()) stdout() else stderr())
  })
}
```
