### ISSUE TITLE
Naive question: additional setup needed for macOS and Windows?

### ISSUE THREAD

**Issue by zkamvar** [r-lib/gert#84]
I saw this paragraph in the README and I was wondering if this means that folks on macOS and Windows need to have homebrew and rtools installed?

> On MacOS and Windows the package is statically linked to the Homebrew and rtools40 build of libgit2. These versions of libgit2 are guaranteed to be properly configured for that operating system, especially when it comes to 3rd party libraries that libgit2 needs to support ssh and TLS (for https).

I'm assuming that additional setup is NOT needed since this is going in the {usethis} backend, but I just wanted to make sure :smiley_cat:

**Comment by jeroen** [comment]
You only need homebrew/rtools if you want to install the dev version of gert from source. You don't need homebrew/rtools if you install the binary package from cran.
