### ISSUE TITLE
`git_ahead_behind()`: set names of returned list?

### ISSUE THREAD

**Issue by pat-s** [r-lib/gert#94]
It would be great if the returned list of `git_ahead_behind()` would be named after the items which triggered the respective block (like git2r does).

```r
    library(gert)
    #> Linking to libgit2 v1.0.1, ssh support: YES
    #> Global config: /Users/pjs/.gitconfig
    #> Default user: pat-s <patrick.schratz@gmail.com>
    library(git2r)

    tmp <- tempfile()
    gert::git_clone("https://github.com/r-lib/gert", tmp)

    # gert
    all_tags_gert <- gert::git_tag_list(repo = tmp)
    tags_ab_gert = purrr::map(all_tags_gert$name, ~ gert::git_ahead_behind(ref = .x, repo = tmp))
    tags_ab_gert
    #> [[1]]
    #> [[1]]$ahead
    #> [1] 0
    #> 
    #> [[1]]$behind
    #> [1] 215
    #> 
    #> 
    #> [[2]]
    #> [[2]]$ahead
    #> [1] 0
    #> 
    #> [[2]]$behind
    #> [1] 206

    # git2r
    repo_head <- git2r::commits(repo = tmp, time = FALSE, n = 1, ref = NULL)[[1]]
    git2r::commits(tmp, time = FALSE, n = 1, ref = NULL)[[1]]
    #> [15c6c1d] 2020-10-03: DWIM all the ref arguments (#93)
    all_tags <- git2r::tags(repo = tmp)
    purrr::map(all_tags, git2r::ahead_behind, repo_head)
    #> $v0.2
    #> [1]   0 215
    #> 
    #> $v0.3
    #> [1]   0 206

```

<sup>Created on 2020-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

    sessioninfo::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                                      
    #>  version  R version 4.0.2 Patched (2020-09-21 r79235)
    #>  os       macOS Big Sur 10.16                        
    #>  system   x86_64, darwin17.0                         
    #>  ui       X11                                        
    #>  language (EN)                                       
    #>  collate  en_US.UTF-8                                
    #>  ctype    en_US.UTF-8                                
    #>  tz       Europe/Berlin                              
    #>  date     2020-10-04                                 
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version     date       lib source                            
    #>  askpass       1.1         2019-01-13 [1] CRAN (R 4.0.0)                    
    #>  assertthat    0.2.1       2019-03-21 [1] CRAN (R 4.0.0)                    
    #>  backports     1.1.10      2020-09-15 [1] CRAN (R 4.0.2)                    
    #>  cli           2.0.2       2020-02-28 [1] CRAN (R 4.0.0)                    
    #>  crayon        1.3.4.9000  2020-09-04 [1] Github (r-lib/crayon@6b3f0c6)     
    #>  credentials   1.3.0       2020-07-21 [1] CRAN (R 4.0.2)                    
    #>  digest        0.6.25      2020-02-23 [1] CRAN (R 4.0.0)                    
    #>  ellipsis      0.3.1       2020-05-15 [1] CRAN (R 4.0.0)                    
    #>  evaluate      0.14        2019-05-28 [1] CRAN (R 4.0.0)                    
    #>  fansi         0.4.1       2020-01-08 [1] CRAN (R 4.0.0)                    
    #>  fs            1.5.0       2020-07-31 [1] CRAN (R 4.0.2)                    
    #>  gert        * 0.3.9007    2020-10-04 [1] Github (r-lib/gert@15c6c1d)       
    #>  git2r       * 0.27.1.9000 2020-06-15 [1] Github (ropensci/git2r@1b1ba56)   
    #>  glue          1.4.2       2020-08-27 [1] CRAN (R 4.0.2)                    
    #>  highr         0.8         2019-03-20 [1] CRAN (R 4.0.0)                    
    #>  htmltools     0.5.0       2020-06-16 [1] CRAN (R 4.0.1)                    
    #>  knitr         1.30        2020-09-22 [1] CRAN (R 4.0.2)                    
    #>  lifecycle     0.2.0       2020-03-06 [1] CRAN (R 4.0.0)                    
    #>  magrittr      1.5         2014-11-22 [1] CRAN (R 4.0.0)                    
    #>  openssl       1.4.3       2020-09-18 [1] CRAN (R 4.0.2)                    
    #>  pillar        1.4.6       2020-07-10 [1] CRAN (R 4.0.2)                    
    #>  pkgconfig     2.0.3       2019-09-22 [1] CRAN (R 4.0.0)                    
    #>  purrr         0.3.4       2020-04-17 [1] CRAN (R 4.0.0)                    
    #>  R.cache       0.14.0      2019-12-06 [1] CRAN (R 4.0.0)                    
    #>  R.methodsS3   1.8.1       2020-08-26 [1] CRAN (R 4.0.2)                    
    #>  R.oo          1.24.0      2020-08-26 [1] CRAN (R 4.0.2)                    
    #>  R.utils       2.10.1      2020-08-26 [1] CRAN (R 4.0.2)                    
    #>  rematch2      2.1.2       2020-05-01 [1] CRAN (R 4.0.0)                    
    #>  reprex        0.3.0.9001  2020-08-24 [1] Github (tidyverse/reprex@d3fc4b8) 
    #>  rlang         0.4.7       2020-07-09 [1] CRAN (R 4.0.2)                    
    #>  rmarkdown     2.4.1       2020-10-02 [1] Github (rstudio/rmarkdown@29aad5e)
    #>  rstudioapi    0.11        2020-02-07 [1] CRAN (R 4.0.0)                    
    #>  sessioninfo   1.1.1       2018-11-05 [1] CRAN (R 4.0.2)                    
    #>  stringi       1.5.3       2020-09-09 [1] CRAN (R 4.0.2)                    
    #>  stringr       1.4.0       2019-02-10 [1] CRAN (R 4.0.0)                    
    #>  styler        1.3.2.9000  2020-07-05 [1] Github (pat-s/styler@51d5200)     
    #>  sys           3.4         2020-07-23 [1] CRAN (R 4.0.2)                    
    #>  tibble        3.0.3       2020-07-10 [1] CRAN (R 4.0.2)                    
    #>  vctrs         0.3.4       2020-08-29 [1] CRAN (R 4.0.2)                    
    #>  withr         2.3.0       2020-09-22 [1] CRAN (R 4.0.2)                    
    #>  xfun          0.18        2020-09-29 [1] CRAN (R 4.0.2)                    
    #>  yaml          2.2.1       2020-02-01 [1] CRAN (R 4.0.0)                    
    #> 
    #> [1] /Users/pjs/Library/R/4.0/library
    #> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

With respect to the example above I am currently using the following workaround:

```r
names(tags_ab_gert) <- all_tags_gert$name
```

**Comment by jeroen** [comment]
I don't understand what you mean, ahead_behind returns a list with `ahead` and `behind`. Can you please show an example of what you want without purrrr?

**Comment by pat-s** [comment]
The following should hopefully make it more clear.

```r
    library(gert)
    #> Linking to libgit2 v1.0.1, ssh support: YES
    #> Global config: /Users/pjs/.gitconfig
    #> Default user: pat-s <patrick.schratz@gmail.com>

    tmp <- tempfile()
    gert::git_clone("https://github.com/r-lib/gert", tmp)

    tag <- gert::git_tag_list(repo = tmp)

    ab <- gert::git_ahead_behind(tag$commit[1], repo = tmp)

    # wish
    wish <- list(ab)
    names(wish) <- tag$name[1]
    wish
    #> $v0.2
    #> $v0.2$ahead
    #> [1] 215
    #> 
    #> $v0.2$behind
    #> [1] 0

    # maybe easier?
    structure(c(
      ref = tag$ref[1], tag = tag$name[1], ahead = ab$ahead,
      behind = ab$behind, commit = tag$commit[1]
    ))
    #>                                        ref 
    #>                           "refs/tags/v0.2" 
    #>                                        tag 
    #>                                     "v0.2" 
    #>                                      ahead 
    #>                                      "215" 
    #>                                     behind 
    #>                                        "0" 
    #>                                     commit 
    #> "742e2cc2ba76ba44dc71349653d3c3b76467eab7"

```

<sup>Created on 2020-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Though this would another level of nesting to the returned list.

Maybe returning a named vector instead of a list would make things easier?

**Comment by jeroen** [comment]
I don't like to add redundant nesting; if you want this you can easily do it yourself in the calling function. 

I could add a field with the input ref to the output list, but it would still be a list (I also don't like named vectors 😀 )

**Comment by pat-s** [comment]
Attaching the names afterwards as shown above also does the trick.

However I still think that the loss of the calling reference (e.g. tag name) in the return of `git_ahead_behind()` is a bit unfortunate.

Anyhow, 90%+ of all gert funs are >> git2r ones ;)

> I also don't like named vectors 😀 

Interesting. For me it is named vectors >> lists, especially because of the naming issues.

**Comment by jennybc** [comment]
I also had some naming hopes (https://github.com/r-lib/gert/issues/65#issue-646748477), which I then just implemented in my wrapper: https://github.com/r-lib/usethis/blob/61422cae03d683024e086f73e6afb4e242b59c0b/R/utils-git.R#L235-L236

**Comment by jeroen** [comment]
@jennybc oh shit I think I broke your wrapper, my last commit adds additional fields to that list. I sent a PR to fix it.

I think that is different from what Pat was proposing though? In his example, tags become the list names, which I don't like because that puts dynamic data in the keys. Imo this is generally bad practice (e.g. tidy data: column names should not contain values).

**Comment by jennybc** [comment]
Yeah, I agree that I don't want data becoming names. I think #65 still basically captures my feelings re: "ahead behind" (which is that I think it's unhelpful vocabulary, but I understand it's coming from upstream = libgit2).
