### ISSUE TITLE
`git_log()$message` contains line-break escape sequences

### ISSUE THREAD

**Issue by pat-s** [r-lib/gert#95]
```r
    library(gert)
    #> Linking to libgit2 v1.0.1, ssh support: YES
    #> Global config: /Users/pjs/.gitconfig
    #> Default user: pat-s <patrick.schratz@gmail.com>
    tmp <- tempfile()
    gert::git_clone("https://github.com/r-lib/gert", tmp)
    gert::git_log(repo = tmp)$message[1:2]

```

    #> [1] "Update NEWS\n"      "Big version bump\n"

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

    sessioninfo::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                                 
    #>  version  R version 4.0.3 RC (2020-10-02 r79292)
    #>  os       macOS Big Sur 10.16                   
    #>  system   x86_64, darwin17.0                    
    #>  ui       X11                                   
    #>  language (EN)                                  
    #>  collate  en_US.UTF-8                           
    #>  ctype    en_US.UTF-8                           
    #>  tz       Europe/Berlin                         
    #>  date     2020-10-06                            
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version    date       lib source                            
    #>  askpass       1.1        2019-01-13 [1] CRAN (R 4.0.0)                    
    #>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                    
    #>  backports     1.1.10     2020-09-15 [1] CRAN (R 4.0.2)                    
    #>  cli           2.0.2      2020-02-28 [1] CRAN (R 4.0.0)                    
    #>  crayon        1.3.4.9000 2020-09-04 [1] Github (r-lib/crayon@6b3f0c6)     
    #>  credentials   1.3.0      2020-07-21 [1] CRAN (R 4.0.2)                    
    #>  digest        0.6.25     2020-02-23 [1] CRAN (R 4.0.0)                    
    #>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.0)                    
    #>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.0)                    
    #>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.0)                    
    #>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                    
    #>  gert        * 0.3.9007   2020-10-05 [1] Github (r-lib/gert@9dd8a15)       
    #>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                    
    #>  highr         0.8        2019-03-20 [1] CRAN (R 4.0.0)                    
    #>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 4.0.1)                    
    #>  knitr         1.30       2020-09-22 [1] CRAN (R 4.0.2)                    
    #>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.0.0)                    
    #>  magrittr      1.5        2014-11-22 [1] CRAN (R 4.0.0)                    
    #>  openssl       1.4.3      2020-09-18 [1] CRAN (R 4.0.2)                    
    #>  pillar        1.4.6      2020-07-10 [1] CRAN (R 4.0.2)                    
    #>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.0)                    
    #>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.0)                    
    #>  R.cache       0.14.0     2019-12-06 [1] CRAN (R 4.0.0)                    
    #>  R.methodsS3   1.8.1      2020-08-26 [1] CRAN (R 4.0.2)                    
    #>  R.oo          1.24.0     2020-08-26 [1] CRAN (R 4.0.2)                    
    #>  R.utils       2.10.1     2020-08-26 [1] CRAN (R 4.0.2)                    
    #>  reprex        0.3.0.9001 2020-08-24 [1] Github (tidyverse/reprex@d3fc4b8) 
    #>  rlang         0.4.7      2020-07-09 [1] CRAN (R 4.0.2)                    
    #>  rmarkdown     2.4.1      2020-10-05 [1] Github (rstudio/rmarkdown@1707d0b)
    #>  rstudioapi    0.11       2020-02-07 [1] CRAN (R 4.0.0)                    
    #>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.2)                    
    #>  stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)                    
    #>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.0)                    
    #>  styler        1.3.2.9000 2020-07-05 [1] Github (pat-s/styler@51d5200)     
    #>  sys           3.4        2020-07-23 [1] CRAN (R 4.0.2)                    
    #>  tibble        3.0.3      2020-07-10 [1] CRAN (R 4.0.2)                    
    #>  vctrs         0.3.4      2020-08-29 [1] CRAN (R 4.0.2)                    
    #>  withr         2.3.0      2020-09-22 [1] CRAN (R 4.0.2)                    
    #>  xfun          0.18       2020-09-29 [1] CRAN (R 4.0.2)                    
    #>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)                    
    #> 
    #> [1] /Users/pjs/Library/R/4.0/library
    #> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by jeroen** [comment]
This is done automatically by libgit2; I think it is actually required by git to include a linebreak at the end.

**Comment by pat-s** [comment]
Thanks. Then I'll adjust to this pattern.
