### ISSUE TITLE
Add `local` argument to `git_branch_list()`

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#98]
In my usage, it would be very handy if `git_branch_list()` had a `local` argument, the same way `git_branch_exists()` does.

**Comment by jeroen** [comment]
OK, should we set the default to `TRUE` as with `git_branch_exists()` to only return local branches by default?

**Comment by jennybc** [comment]
I'm OK with "no specification" --> "all branches", `TRUE` --> local only, `FALSE` --> remote only. Although it feels like `git_branch_exists()` and this function should be the same with respect to `local`, i.e. have same default.

I do question the argument order, though. There's a strong convention for `repo` being last and, in particular, `local` comes before `repo` in `git_branch_exists()`. Look at all the other `git_branch_*()` function signatures:

https://docs.ropensci.org/gert/reference/git_branch.html

**Comment by jeroen** [comment]
Good catch, that wasn't on purpose.

**Comment by jennybc** [comment]
This does affect some usethis calls, but as of today I've adopted a strict policy of always calling with `repo =`, to be more resilient to signature changes.

**Comment by jeroen** [comment]
OK thanks! I also just added this recommendation to the documentation of `?repo`
